// SPDX-License-Identifier: MIT
// HexSpindle original executable/binary forensic parsers. No new third-party runtime dependencies.
import { md5 } from './_md5.js';
import { text, latin1, utf16, hex, safeJson, need, has, u16le, u16be, u32le, u32be, u64le, u64be, i32le, fixedAscii, asciiz, utf16z, entropy, printableAsciiStrings, printableUtf16Strings, extractIocsFromText } from './_common.js';
import { listZip, findZipEntry, zipEntryBytes } from './_zip.js';

function md5hex(bytes){return [...md5(bytes)].map(b=>b.toString(16).padStart(2,'0')).join('');}
function pe(data){
  if(data[0]!==0x4d||data[1]!==0x5a)throw new Error('Not a PE file (MZ missing)'); const peOff=u32le(data,0x3c); need(data,peOff,24,'PE header'); if(data[peOff]!==0x50||data[peOff+1]!==0x45||data[peOff+2]!==0||data[peOff+3]!==0)throw new Error('PE signature missing');
  const nsec=u16le(data,peOff+6), optSize=u16le(data,peOff+20), opt=peOff+24, magic=u16le(data,opt), plus=magic===0x20b; if(!plus&&magic!==0x10b)throw new Error('Unsupported PE optional-header magic');
  const dd=opt+(plus?112:96), secOff=opt+optSize, dirs=[]; const dirCount=Math.min(u32le(data,opt+(plus?108:92)),16); for(let i=0;i<dirCount;i++)dirs.push({rva:u32le(data,dd+i*8),size:u32le(data,dd+i*8+4)});
  const sections=[]; for(let i=0;i<nsec;i++){const o=secOff+i*40;if(!has(data,o,40))break;sections.push({name:fixedAscii(data,o,8),virtualSize:u32le(data,o+8),virtualAddress:u32le(data,o+12),rawSize:u32le(data,o+16),rawPointer:u32le(data,o+20),characteristics:u32le(data,o+36)});}
  function rvaToOff(rva){if(rva<secOff+nsec*40)return rva;for(const s of sections){const span=Math.max(s.virtualSize,s.rawSize);if(rva>=s.virtualAddress&&rva<s.virtualAddress+span)return s.rawPointer+(rva-s.virtualAddress);}return null;}
  return {peOff,opt,plus,nsec,optSize,dd,dirs,sections,rvaToOff,machine:u16le(data,peOff+4),timestamp:u32le(data,peOff+8),characteristics:u16le(data,peOff+22)};
}
function peImports(data,p){const d=p.dirs[1];if(!d?.rva)return[];let off=p.rvaToOff(d.rva);if(off==null)return[];const out=[];for(let guard=0;guard<4096&&has(data,off,20);guard++,off+=20){const oft=u32le(data,off),nameRva=u32le(data,off+12),ft=u32le(data,off+16);if(!oft&&!nameRva&&!ft)break;const no=p.rvaToOff(nameRva);const dll=no==null?'':asciiz(data,no,512);const thunkRva=oft||ft;let to=p.rvaToOff(thunkRva);const funcs=[];const step=p.plus?8:4, ordinalFlag=p.plus?0x8000000000000000n:0x80000000n;for(let j=0;j<65536&&to!=null&&has(data,to,step);j++,to+=step){const v=p.plus?u64le(data,to):BigInt(u32le(data,to));if(v===0n)break;if(v&ordinalFlag)funcs.push({ordinal:Number(v&0xffffn)});else{const hn=p.rvaToOff(Number(v));if(hn!=null&&has(data,hn,3))funcs.push({hint:u16le(data,hn),name:asciiz(data,hn+2,1024)});}}out.push({dll,functions:funcs});}return out;}
export function peImportHash(data){const p=pe(data), imports=peImports(data,p), parts=[];for(const d of imports){let lib=d.dll.toLowerCase().replace(/\.(dll|ocx|sys)$/,'');for(const f of d.functions){const name=f.name?f.name.toLowerCase():`ord${f.ordinal}`;parts.push(`${lib}.${name}`);}}const canonical=parts.join(',');return safeJson({imphash:md5hex(new TextEncoder().encode(canonical)),canonical,imports:imports.map(x=>({dll:x.dll,count:x.functions.length})) ,note:'Ordinal imports are represented as ordNNN. Named-import hashes match the conventional pefile/Mandiant ordering.'});}
export function peRichHeader(data){const rich=latin1(data).indexOf('Rich');if(rich<0||!has(data,rich+4,4))throw new Error('Rich marker not found');const key=u32le(data,rich+4);let dans=-1;for(let p=rich-4;p>=0x40;p-=4){if((u32le(data,p)^key)===0x536e6144){dans=p;break;}}if(dans<0)throw new Error('DanS marker not found before Rich header');const rows=[];for(let p=dans+16;p+8<=rich;p+=8){const compid=u32le(data,p)^key,count=u32le(data,p+4)^key;rows.push({productId:(compid>>>16)&0xffff,build:compid&0xffff,count});}return safeJson({offset:dans,richOffset:rich,xorKey:'0x'+key.toString(16).padStart(8,'0'),entries:rows});}
export function peAuthenticode(data){const p=pe(data), d=p.dirs[4];if(!d?.rva||!d.size)return safeJson({present:false});const off=d.rva; if(!has(data,off,8))throw new Error('PE security directory points outside file');const certs=[];let q=off,end=Math.min(data.length,off+d.size);while(q+8<=end){const len=u32le(data,q),rev=u16le(data,q+4),type=u16le(data,q+6);if(len<8||q+len>end)break;certs.push({offset:q,length:len,revision:'0x'+rev.toString(16),certificateType:type===2?'WIN_CERT_TYPE_PKCS_SIGNED_DATA':type,pkcs7Bytes:len-8,sha256Note:'Signature trust/chain validation is intentionally not claimed by this structural inspector.'});q+=(len+7)&~7;}return safeJson({present:certs.length>0,directoryOffset:off,directorySize:d.size,certificates:certs});}
export function peSections(data){const p=pe(data),rows=p.sections.map((s,i)=>{const bytes=has(data,s.rawPointer,s.rawSize)?data.subarray(s.rawPointer,s.rawPointer+s.rawSize):new Uint8Array();const flags=[];if(s.characteristics&0x20000000)flags.push('EXECUTE');if(s.characteristics&0x40000000)flags.push('READ');if(s.characteristics&0x80000000)flags.push('WRITE');return{index:i,name:s.name,virtualAddress:'0x'+s.virtualAddress.toString(16),virtualSize:s.virtualSize,rawPointer:s.rawPointer,rawSize:s.rawSize,entropy:+entropy(bytes).toFixed(4),permissions:flags.join('|'),wx:!!((s.characteristics&0x20000000)&&(s.characteristics&0x80000000))};});const overlaps=[];const sorted=[...p.sections].filter(x=>x.rawSize).sort((a,b)=>a.rawPointer-b.rawPointer);for(let i=1;i<sorted.length;i++)if(sorted[i].rawPointer<sorted[i-1].rawPointer+sorted[i-1].rawSize)overlaps.push([sorted[i-1].name,sorted[i].name]);return safeJson({sections:rows,overlaps});}
export function pePackerHeuristics(data){const p=pe(data),s=JSON.parse(peSections(data)),ind=[];for(const x of s.sections){if(x.entropy>=7.2)ind.push({indicator:`High entropy section ${x.name}`,weight:2});if(x.wx)ind.push({indicator:`Writable+executable section ${x.name}`,weight:2});if(/upx|aspack|mpress|petite|themida|vmp/i.test(x.name))ind.push({indicator:`Packer-like section name ${x.name}`,weight:3});}const imports=peImports(data,p);const fn=imports.reduce((n,x)=>n+x.functions.length,0);if(imports.length<=2&&fn<15)ind.push({indicator:'Very small import table',weight:1});const overlay=Math.max(0,data.length-Math.max(...p.sections.map(x=>x.rawPointer+x.rawSize),0));if(overlay>65536)ind.push({indicator:`Large overlay (${overlay} bytes)`,weight:1});return safeJson({score:ind.reduce((a,x)=>a+x.weight,0),indicators:ind,overlayBytes:overlay,interpretation:'Heuristics only; a positive score is not proof of packing or maliciousness.'});}
export function peResources(data){const p=pe(data),d=p.dirs[2];if(!d?.rva)return safeJson([]);const base=p.rvaToOff(d.rva);if(base==null)throw new Error('Resource directory RVA is unmapped');const rows=[];const TYPE={1:'CURSOR',2:'BITMAP',3:'ICON',4:'MENU',5:'DIALOG',6:'STRING',9:'ACCELERATOR',10:'RCDATA',12:'GROUP_CURSOR',14:'GROUP_ICON',16:'VERSION',24:'MANIFEST'};const seen=new Set();function walk(dirOff,path=[],depth=0){if(depth>8||seen.has(dirOff)||!has(data,dirOff,16))return;seen.add(dirOff);const n=u16le(data,dirOff+12)+u16le(data,dirOff+14);for(let i=0;i<n;i++){const e=dirOff+16+i*8;if(!has(data,e,8))break;const nameRaw=u32le(data,e),val=u32le(data,e+4);let name;if(nameRaw&0x80000000){const no=base+(nameRaw&0x7fffffff);name=has(data,no,2)?utf16(data.subarray(no+2,no+2+u16le(data,no)*2)):'';}else{name=nameRaw;if(path.length===0)name=TYPE[name]||name;}if(val&0x80000000)walk(base+(val&0x7fffffff),[...path,name],depth+1);else{const de=base+val;if(!has(data,de,16))continue;const rva=u32le(data,de),size=u32le(data,de+4),codePage=u32le(data,de+8),fo=p.rvaToOff(rva);rows.push({path:[...path,name].join('/'),rva:'0x'+rva.toString(16),fileOffset:fo,size,codePage,preview:fo!=null&&has(data,fo,Math.min(size,64))?hex(data.subarray(fo,fo+Math.min(size,64))):''});}}}walk(base);return safeJson(rows);}

function metadataRoot(data){const p=pe(data),cli=p.dirs[14];if(!cli?.rva)throw new Error('PE has no CLR Runtime Header');const co=p.rvaToOff(cli.rva);if(co==null||!has(data,co,24))throw new Error('CLR header unmapped');const metaRva=u32le(data,co+8),metaSize=u32le(data,co+12),mo=p.rvaToOff(metaRva);if(mo==null||!has(data,mo,20))throw new Error('CLR metadata unmapped');if(u32le(data,mo)!==0x424a5342)throw new Error('CLR metadata BSJB signature missing');const verLen=u32le(data,mo+12),version=latin1(data.subarray(mo+16,mo+16+verLen)).replace(/\0+$/,'');let q=(mo+16+verLen+3)&~3;q+=2;const streams=u16le(data,q);q+=2;const list=[];for(let i=0;i<streams;i++){const off=u32le(data,q),size=u32le(data,q+4);let nend=q+8;while(nend<data.length&&data[nend])nend++;const name=latin1(data.subarray(q+8,nend));q=(nend+4)&~3;list.push({name,offset:mo+off,size,relativeOffset:off});}return{p,cliOffset:co,metaOffset:mo,metaSize,version,streams:list};}
function heapStrings(data,s){const out=[];let p=s.offset+1,end=Math.min(data.length,s.offset+s.size);while(p<end){let z=p;while(z<end&&data[z])z++;if(z>p){const v=text(data.subarray(p,z));if(v)out.push({offset:p-s.offset,value:v});}p=z+1;}return out;}
function readCompressedUInt(data,p){const a=data[p];if(a<0x80)return[a,1];if(a<0xc0)return[((a&0x3f)<<8)|data[p+1],2];return[((a&0x1f)<<24)|(data[p+1]<<16)|(data[p+2]<<8)|data[p+3],4];}
export function dotnetMetadata(data){const m=metadataRoot(data),strings=m.streams.find(x=>x.name==='#Strings');const hs=strings?heapStrings(data,strings):[];const assemblyish=hs.filter(x=>/^[A-Za-z_][\w. -]{2,120}$/.test(x.value)).map(x=>x.value);return safeJson({runtimeVersion:m.version,metadataSize:m.metaSize,streams:m.streams.map(({name,relativeOffset,size})=>({name,offset:relativeOffset,size})),candidateIdentifiers:[...new Set(assemblyish)].slice(0,500),note:'Metadata stream boundaries are parsed structurally. Candidate identifiers come from the #Strings heap; no assembly-reference claim is made solely from an unbound string.'});}
export function dotnetUserStrings(data){const m=metadataRoot(data),s=m.streams.find(x=>x.name==='#US');if(!s)return safeJson([]);const out=[];let p=s.offset+1,end=Math.min(data.length,s.offset+s.size);while(p<end){const [len,n]=readCompressedUInt(data,p);if(!len){p+=n;continue;}const start=p+n;if(start+len>end)break;const body=data.subarray(start,start+Math.max(0,len-1));out.push({offset:p-s.offset,value:utf16(body)});p=start+len;}return safeJson(out);}

function machoHeader(data){const magic=u32be(data,0);let le=false,is64=false;if(magic===0xfeedface){le=false;is64=false;}else if(magic===0xfeedfacf){le=false;is64=true;}else if(magic===0xcefaedfe){le=true;is64=false;}else if(magic===0xcffaedfe){le=true;is64=true;}else throw new Error('Not a thin Mach-O file (FAT/universal wrapper not supported by this operation)');const dv=new DataView(data.buffer,data.byteOffset,data.byteLength);const u32=(o)=>dv.getUint32(o,le);const i32=(o)=>dv.getInt32(o,le);const cputype=i32(4),cpusubtype=i32(8),filetype=u32(12),ncmds=u32(16),sizeofcmds=u32(20),flags=u32(24),headerSize=is64?32:28;const cmds=[];let p=headerSize;for(let i=0;i<ncmds;i++){if(!has(data,p,8))break;const cmd=u32(p),size=u32(p+4);if(size<8||!has(data,p,size))break;cmds.push({cmd,size,offset:p});p+=size;}return{le,is64,cputype,cpusubtype,filetype,ncmds,sizeofcmds,flags,cmds,u32};}
const MACHO_CMDS={1:'LC_SEGMENT',2:'LC_SYMTAB',11:'LC_DYSYMTAB',12:'LC_LOAD_DYLIB',13:'LC_ID_DYLIB',14:'LC_LOAD_DYLINKER',0x19:'LC_SEGMENT_64',0x1d:'LC_CODE_SIGNATURE',0x22:'LC_DYLD_INFO',0x80000022:'LC_DYLD_INFO_ONLY',0x80000028:'LC_MAIN',0x32:'LC_BUILD_VERSION'};
export function machoHeaderInspect(data){const m=machoHeader(data),rows=m.cmds.map(c=>({cmd:'0x'+c.cmd.toString(16),name:MACHO_CMDS[c.cmd]||'OTHER',size:c.size,offset:c.offset}));return safeJson({bits:m.is64?64:32,endian:m.le?'little':'big',cpuType:m.cputype,cpuSubtype:m.cpusubtype,fileType:m.filetype,flags:'0x'+m.flags.toString(16),loadCommands:rows});}
export function machoCodeSignature(data){const m=machoHeader(data),c=m.cmds.find(x=>x.cmd===0x1d);if(!c)return safeJson({present:false});const off=m.u32(c.offset+8),size=m.u32(c.offset+12);if(!has(data,off,size))throw new Error('Mach-O code signature range is outside file');const blob=data.subarray(off,off+size);const magic=u32be(blob,0);const out={present:true,dataOffset:off,dataSize:size,magic:'0x'+magic.toString(16),blobs:[]};if(magic===0xfade0cc0&&blob.length>=12){const count=u32be(blob,8);for(let i=0;i<count&&12+i*8+8<=blob.length;i++){const type=u32be(blob,12+i*8),bo=u32be(blob,16+i*8);if(!has(blob,bo,8))continue;out.blobs.push({slotType:type,offset:bo,magic:'0x'+u32be(blob,bo).toString(16),length:u32be(blob,bo+4)});}}out.note='Embedded code-signing structures are inspected; trust/notarization validation is not performed.';return safeJson(out);}

function elf(data){if(!(data[0]===0x7f&&data[1]===0x45&&data[2]===0x4c&&data[3]===0x46))throw new Error('Not ELF');const cls=data[4],le=data[5]===1;if(cls!==1&&cls!==2)throw new Error('Unknown ELF class');const dv=new DataView(data.buffer,data.byteOffset,data.byteLength);const u16=o=>dv.getUint16(o,le),u32=o=>dv.getUint32(o,le),u64=o=>dv.getBigUint64(o,le);const shoff=Number(cls===2?u64(40):u32(32)),shentsize=u16(cls===2?58:46),shnum=u16(cls===2?60:48),shstrndx=u16(cls===2?62:50);const secs=[];for(let i=0;i<shnum;i++){const o=shoff+i*shentsize;if(!has(data,o,shentsize))break;const nameOff=u32(o),type=u32(o+4),flags=cls===2?u64(o+8):BigInt(u32(o+8)),addr=cls===2?u64(o+16):BigInt(u32(o+12)),offset=Number(cls===2?u64(o+24):u32(o+16)),size=Number(cls===2?u64(o+32):u32(o+20)),link=u32(o+(cls===2?40:24)),info=u32(o+(cls===2?44:28)),entsize=Number(cls===2?u64(o+56):u32(o+36));secs.push({index:i,o,nameOff,type,flags,addr,offset,size,link,info,entsize,name:''});}const shstr=secs[shstrndx];if(shstr&&has(data,shstr.offset,shstr.size)){for(const s of secs)s.name=asciiz(data,shstr.offset+s.nameOff,4096);}return{cls,le,secs,u16,u32,u64};}
export function elfSymbolsRelocations(data){const e=elf(data),symbols=[];for(const s of e.secs.filter(x=>x.type===2||x.type===11)){const str=e.secs[s.link];if(!str||!s.entsize)continue;for(let o=s.offset;o+s.entsize<=s.offset+s.size;o+=s.entsize){const nameOff=e.u32(o);let info,shndx,value,size;if(e.cls===2){info=data[o+4];shndx=e.u16(o+6);value=e.u64(o+8);size=e.u64(o+16);}else{value=BigInt(e.u32(o+4));size=BigInt(e.u32(o+8));info=data[o+12];shndx=e.u16(o+14);}const name=str&&nameOff<str.size?asciiz(data,str.offset+nameOff,4096):'';if(name)symbols.push({table:s.name,name,binding:info>>4,type:info&15,sectionIndex:shndx,value:'0x'+value.toString(16),size:size.toString()});}}
  const relocs=[];for(const s of e.secs.filter(x=>x.type===4||x.type===9)){const ent=s.entsize|| (e.cls===2?(s.type===4?24:16):(s.type===4?12:8));for(let o=s.offset;o+ent<=s.offset+s.size;o+=ent){if(e.cls===2){const ro=e.u64(o),ri=e.u64(o+8);relocs.push({section:s.name,offset:'0x'+ro.toString(16),symbol:Number(ri>>32n),type:Number(ri&0xffffffffn)});}else{const ro=e.u32(o),ri=e.u32(o+4);relocs.push({section:s.name,offset:'0x'+ro.toString(16),symbol:ri>>>8,type:ri&0xff});}if(relocs.length>20000)break;}}return safeJson({symbols:symbols.slice(0,20000),relocations:relocs.slice(0,20000)});}
export function elfNotesBuildId(data){const e=elf(data),notes=[];for(const s of e.secs.filter(x=>x.type===7)){let p=s.offset,end=s.offset+s.size;while(p+12<=end){const namesz=e.u32(p),descsz=e.u32(p+4),type=e.u32(p+8);p+=12;const name=latin1(data.subarray(p,p+namesz)).replace(/\0+$/,'');p+=(namesz+3)&~3;const desc=data.subarray(p,p+descsz);p+=(descsz+3)&~3;notes.push({section:s.name,name,type,descriptionHex:hex(desc),buildId:name==='GNU'&&type===3?hex(desc):undefined});}}return safeJson(notes);}

export async function jarMetadata(data){const entries=listZip(data);const man=await findZipEntry(data,'META-INF/MANIFEST.MF');const manifest=man?text(man):'';const classes=entries.filter(x=>x.name.endsWith('.class')).map(x=>x.name.replace(/\.class$/,'').replace(/\//g,'.'));const deps=[];for(const line of manifest.split(/\r?\n/)){if(/^(Class-Path|Automatic-Module-Name|Main-Class|Implementation-|Bundle-)/i.test(line))deps.push(line);}return safeJson({entries:entries.length,manifest,manifestHighlights:deps,classCount:classes.length,classes:classes.slice(0,5000)});}

function readLen8(b,p){let v=b[p++];if(v&0x80){v=((v&0x7f)<<8)|b[p++];}return[v,p];}function readLen16(b,p){let v=u16le(b,p);p+=2;if(v&0x8000){v=((v&0x7fff)<<16)|u16le(b,p);p+=2;}return[v,p];}
function axmlStringPool(data,off){const headerSize=u16le(data,off+2),size=u32le(data,off+4),count=u32le(data,off+8),flags=u32le(data,off+16),stringsStart=u32le(data,off+20),utf8flag=!!(flags&0x100),strings=[];for(let i=0;i<count;i++){const so=u32le(data,off+headerSize+i*4);let p=off+stringsStart+so;if(utf8flag){[,p]=readLen8(data,p);let bl;[bl,p]=readLen8(data,p);strings.push(text(data.subarray(p,p+bl)));}else{let chars;[chars,p]=readLen16(data,p);strings.push(utf16(data.subarray(p,p+chars*2)));}}return{strings,size};}
function typedValue(data,type,val,strings){switch(type){case 0x03:return strings[val]??`@string#${val}`;case 0x10:return val;case 0x11:return '0x'+val.toString(16);case 0x12:return !!val;case 0x01:return '@0x'+val.toString(16);default:return val;}}
export function apkManifest(data){return (async()=>{const manifestEntry=listZip(data).find(x=>x.name==='AndroidManifest.xml');if(!manifestEntry)throw new Error('AndroidManifest.xml not found in APK/ZIP');const b=await zipEntryBytes(data,manifestEntry);if(b[0]===0x3c)return text(b);if(u16le(b,0)!==0x0003)throw new Error('AndroidManifest.xml is neither text XML nor Android binary XML');let p=u16le(b,2),strings=[];const lines=[],stack=[];while(p+8<=b.length){const type=u16le(b,p),hs=u16le(b,p+2),size=u32le(b,p+4);if(size<8||p+size>b.length)break;if(type===0x0001){const sp=axmlStringPool(b,p);strings=sp.strings;}else if(type===0x0102&&hs>=16){const ext=p+16,ns=u32le(b,ext),nameIdx=u32le(b,ext+4),attrStart=u16le(b,ext+8),attrSize=u16le(b,ext+10),attrCount=u16le(b,ext+12),name=strings[nameIdx]??`#${nameIdx}`,attrs=[];let a=p+16+attrStart;for(let i=0;i<attrCount&&a+20<=p+size;i++,a+=attrSize||20){const ans=u32le(b,a),an=u32le(b,a+4),raw=u32le(b,a+8),vtype=b[a+15],vdata=u32le(b,a+16);const key=(ans!==0xffffffff?(strings[ans]?strings[ans]+':':''):'')+(strings[an]??`#${an}`);const value=raw!==0xffffffff?(strings[raw]??''):typedValue(b,vtype,vdata,strings);attrs.push([key,value]);}lines.push('  '.repeat(stack.length)+`<${name}${attrs.map(([k,v])=>` ${k}="${String(v).replace(/&/g,'&amp;').replace(/"/g,'&quot;')}"`).join('')}>`);stack.push(name);}else if(type===0x0103&&hs>=16){const nameIdx=u32le(b,p+20),name=strings[nameIdx]??stack.at(-1)??'node';stack.pop();lines.push('  '.repeat(stack.length)+`</${name}>`);}p+=size;}return lines.join('\n');})();}

function uleb(data,p){let v=0,shift=0,n=0;do{const b=data[p+n];v|=(b&0x7f)<<shift;shift+=7;n++;if(!(b&0x80))break;}while(n<5);return[v,n];}
export function dexMetadata(data){if(fixedAscii(data,0,4)!=='dex\n')throw new Error('Not a DEX file');const version=fixedAscii(data,4,3),stringsSize=u32le(data,56),stringsOff=u32le(data,60),typeSize=u32le(data,64),typeOff=u32le(data,68),methodSize=u32le(data,88),methodOff=u32le(data,92),classSize=u32le(data,96),classOff=u32le(data,100);const strings=[];for(let i=0;i<stringsSize&&i<200000;i++){const so=u32le(data,stringsOff+i*4);const [,n]=uleb(data,so);let e=so+n;while(e<data.length&&data[e])e++;strings.push(text(data.subarray(so+n,e)));}const types=[];for(let i=0;i<typeSize;i++){const si=u32le(data,typeOff+i*4);types.push(strings[si]??`#${si}`);}const methods=[];for(let i=0;i<methodSize&&i<200000;i++){const o=methodOff+i*8,ci=u16le(data,o),pi=u16le(data,o+2),ni=u32le(data,o+4);methods.push({class:types[ci]??ci,protoIndex:pi,name:strings[ni]??ni});}const classes=[];for(let i=0;i<classSize;i++){const o=classOff+i*32,ci=u32le(data,o),access=u32le(data,o+4),superIdx=u32le(data,o+8),sourceIdx=u32le(data,o+16);classes.push({class:types[ci]??ci,superClass:superIdx===0xffffffff?null:(types[superIdx]??superIdx),source:sourceIdx===0xffffffff?null:(strings[sourceIdx]??sourceIdx),accessFlags:'0x'+access.toString(16)});}return safeJson({version,stringCount:stringsSize,typeCount:typeSize,methodCount:methodSize,classCount:classSize,classes:classes.slice(0,50000),methods:methods.slice(0,50000),strings:strings.slice(0,50000)});}

export function analyzeSuspiciousScript(data){const s=text(data);const rules=[['PowerShell encoded command',/-(?:enc|encodedcommand)\s+[A-Za-z0-9+/=]{20,}/ig,3],['PowerShell download cradle',/(?:Invoke-WebRequest|iwr|wget|curl|Net\.WebClient|DownloadString|DownloadFile)/ig,2],['PowerShell dynamic execution',/(?:Invoke-Expression|\biex\b|ScriptBlock\.Create)/ig,2],['AMSI bypass indicator',/(?:AmsiUtils|amsiInitFailed|amsiContext)/ig,3],['Reflection/dynamic load',/(?:Reflection\.Assembly|Assembly\.Load|GetDelegateForFunctionPointer)/ig,2],['JavaScript eval',/\b(?:eval|Function)\s*\(/g,2],['String.fromCharCode obfuscation',/String\.fromCharCode\s*\(/g,1],['WScript.Shell',/WScript\.Shell/ig,2],['Shell command execution',/(?:cmd\.exe|powershell(?:\.exe)?|wscript\.exe|cscript\.exe|mshta\.exe)/ig,2],['Long Base64-like blob',/[A-Za-z0-9+/]{200,}={0,2}/g,1],['Hex escape density',/(?:\\x[0-9a-fA-F]{2}){8,}/g,1]];const hits=[];for(const[name,re,w]of rules){let m;while((m=re.exec(s))&&hits.length<2000)hits.push({rule:name,weight:w,offset:m.index,match:m[0].slice(0,180)});}return safeJson({score:hits.reduce((a,x)=>a+x.weight,0),hits,interpretation:'Static heuristics only. Matches require analyst review and are not a malware verdict.'});}
export function extractEmbeddedConfig(data){const s=text(data);const iocs=extractIocsFromText(s);const kv=[];for(const line of s.split(/\r?\n/)){const m=/^\s*([A-Za-z_][\w.-]{1,63})\s*[:=]\s*(.{1,500})\s*$/.exec(line);if(m)kv.push({key:m[1],value:m[2]});}const json=[];for(const m of s.matchAll(/\{[^{}]{10,2000}\}/g)){try{json.push(JSON.parse(m[0]));}catch{}}return safeJson({iocs,keyValues:kv.slice(0,2000),jsonObjects:json.slice(0,100),note:'Generic configuration extractor. It reports structured candidates rather than attributing them to a malware family.'});}
