// SPDX-License-Identifier: MIT
// HexSpindle original browser/user-activity forensic parsers.
import { text, safeJson, webkitToIso, unixToIso, parseJsonish } from './_common.js';
import { SQLiteReader } from './_sqlite.js';

function tableIf(db,name,limit=20000){try{return db.table(name,limit);}catch{return[];}}
function num(v){const n=Number(v);return Number.isFinite(n)?n:null;}
export function parseChromeHistory(data){const db=new SQLiteReader(data),urls=tableIf(db,'urls',100000),visits=tableIf(db,'visits',200000);const byId=new Map(urls.map(x=>[String(x.id??x._rowid),x]));const out=visits.map(v=>{const u=byId.get(String(v.url))||{};return{visitId:v.id??v._rowid,url:u.url||'',title:u.title||'',visitTime:webkitToIso(v.visit_time),fromVisit:v.from_visit,transition:v.transition,visitDurationMicroseconds:v.visit_duration,visitCount:u.visit_count,typedCount:u.typed_count,lastVisitTime:webkitToIso(u.last_visit_time)};});if(!out.length)return safeJson(urls.map(u=>({url:u.url,title:u.title,visitCount:u.visit_count,typedCount:u.typed_count,lastVisitTime:webkitToIso(u.last_visit_time)})));return safeJson(out);}
export function parseFirefoxHistory(data){const db=new SQLiteReader(data),places=tableIf(db,'moz_places',100000),visits=tableIf(db,'moz_historyvisits',200000),byId=new Map(places.map(x=>[String(x.id??x._rowid),x]));return safeJson(visits.map(v=>{const p=byId.get(String(v.place_id))||{};return{visitId:v.id??v._rowid,url:p.url||'',title:p.title||'',visitTime:unixToIso(Number(v.visit_date||0)/1e6),fromVisit:v.from_visit,visitType:v.visit_type,visitCount:p.visit_count,lastVisitTime:unixToIso(Number(p.last_visit_date||0)/1e6)};}));}
export function parseChromiumDownloads(data){const db=new SQLiteReader(data),dls=tableIf(db,'downloads',100000),chains=tableIf(db,'downloads_url_chains',200000),by=new Map();for(const c of chains){const id=String(c.id),a=by.get(id)||[];a.push({index:c.chain_index,url:c.url});by.set(id,a);}return safeJson(dls.map(d=>({id:d.id??d._rowid,targetPath:d.target_path||d.current_path,startTime:webkitToIso(d.start_time),endTime:webkitToIso(d.end_time),receivedBytes:d.received_bytes,totalBytes:d.total_bytes,state:d.state,dangerType:d.danger_type,interruptReason:d.interrupt_reason,referrer:d.referrer,siteUrl:d.site_url,tabUrl:d.tab_url,mimeType:d.mime_type,originalMimeType:d.original_mime_type,urlChain:(by.get(String(d.id??d._rowid))||[]).sort((a,b)=>a.index-b.index).map(x=>x.url)})));}
export function parseCookieMetadata(data){const db=new SQLiteReader(data);let rows=tableIf(db,'cookies',100000),browser='Chromium';if(!rows.length){rows=tableIf(db,'moz_cookies',100000);browser='Firefox';}return safeJson(rows.map(c=>browser==='Chromium'?{browser,host:c.host_key,name:c.name,path:c.path,creationTime:webkitToIso(c.creation_utc),expiresTime:webkitToIso(c.expires_utc),lastAccessTime:webkitToIso(c.last_access_utc),lastUpdateTime:webkitToIso(c.last_update_utc),secure:!!c.is_secure,httpOnly:!!c.is_httponly,sameSite:c.samesite,sourceScheme:c.source_scheme,valuePresent:!!c.value,encryptedValueBytes:c.encrypted_value?.bytes??null}:{browser,host:c.host,name:c.name,path:c.path,creationTime:unixToIso(Number(c.creationTime||0)/1e6),expiry:c.expiry?unixToIso(Number(c.expiry)):null,lastAccessed:unixToIso(Number(c.lastAccessed||0)/1e6),secure:!!c.isSecure,httpOnly:!!c.isHttpOnly,sameSite:c.sameSite,originAttributes:c.originAttributes,valuePresent:!!c.value}));}

export function analyzeChromiumPreferences(data){const j=JSON.parse(text(data));const ext=j.extensions?.settings||{},extensions=[];for(const [id,x] of Object.entries(ext))extensions.push({id,state:x.state,fromWebstore:x.from_webstore,installTime:x.install_time,manifestName:x.manifest?.name,version:x.manifest?.version,permissions:x.manifest?.permissions||[],hostPermissions:x.manifest?.host_permissions||[],path:x.path,location:x.location,disableReasons:x.disable_reasons});const risky=[];for(const x of extensions){const perms=[...(x.permissions||[]),...(x.hostPermissions||[])].join(' ');if(/<all_urls>|webRequest|webRequestBlocking|debugger|nativeMessaging|proxy|management|cookies|history/i.test(perms))risky.push({id:x.id,name:x.manifestName,permissions:x.permissions,hostPermissions:x.hostPermissions});}return safeJson({homepage:j.homepage,homepageIsNtp:j.homepage_is_newtabpage,defaultSearchProvider:j.default_search_provider,download:j.download,proxy:j.proxy,profile:j.profile?.name,extensions,riskyExtensions:risky});}
export function analyzeChromiumExtensionManifest(data){const j=JSON.parse(text(data)),p=[...(j.permissions||[]),...(j.host_permissions||[]),...(j.optional_permissions||[])],high=['<all_urls>','debugger','nativeMessaging','proxy','management','webRequestBlocking','cookies','history','downloads','clipboardRead','clipboardWrite'];const flags=high.filter(x=>p.includes(x)||p.some(v=>x==='<all_urls>'&&/\*:\/\/\*\/\*/.test(v)));return safeJson({name:j.name,version:j.version,manifestVersion:j.manifest_version,description:j.description,permissions:j.permissions||[],hostPermissions:j.host_permissions||[],background:j.background,contentScripts:j.content_scripts,externallyConnectable:j.externally_connectable,updateUrl:j.update_url,riskFlags:flags,review:flags.length?'Elevated permissions warrant review; this is not a maliciousness verdict.':'No high-risk permission from the local heuristic list.'});}
export function analyzeFirefoxExtensions(data){const j=JSON.parse(text(data)),arr=j.addons||j.extensions||j;const a=Array.isArray(arr)?arr:Object.values(arr||{});return safeJson(a.map(x=>({id:x.id||x.defaultLocale?.name,name:x.defaultLocale?.name||x.name,version:x.version,type:x.type,active:x.active,visible:x.visible,location:x.location,path:x.path,installDate:x.installDate,updateDate:x.updateDate,signedState:x.signedState,foreignInstall:x.foreignInstall,userDisabled:x.userDisabled,appDisabled:x.appDisabled,permissions:x.userPermissions?.permissions||x.permissions||[],origins:x.userPermissions?.origins||[]})));}
export function parseWindowsTimeline(data){const db=new SQLiteReader(data),schema=db.master().filter(x=>x.type==='table').map(x=>x.name);const candidates=schema.filter(n=>/Activity/i.test(n)),out=[];for(const t of candidates){for(const r of tableIf(db,t,100000)){const x={table:t,...r};for(const k of Object.keys(x)){const lk=k.toLowerCase();if(/timestamp|starttime|endtime|lastmodified|created/.test(lk)&&typeof x[k]==='number'){const v=x[k];if(v>1e15)x[k+'Iso']=webkitToIso(v);else if(v>1e9)x[k+'Iso']=unixToIso(v);}}out.push(x);}}return safeJson({tables:candidates,records:out});}

export function parseStartupArtifactsJson(data){const j=parseJsonish(data),arr=Array.isArray(j)?j:(j?[j]:[]);return safeJson(arr.map(x=>({source:x.source||x.artifact||'unknown',name:x.name||x.valueName||x.service||'',path:x.path||x.command||x.imagePath||x.target||'',user:x.user||x.sid||'',timestamp:x.timestamp||x.lastWrite||'',enabled:x.enabled??true})));}
