// SPDX-License-Identifier: MIT
// Concise, locally bundled Windows security-auditing event reference.
// Microsoft 2016 Windows 10/Server 2016 auditing reference: https://www.microsoft.com/en-us/download/details.aspx?id=52630
// Supplemental IDs cross-checked with https://www.ultimatewindowssecurity.com/securitylog/encyclopedia/default.aspx
// The original Microsoft document is NOT redistributed; these are condensed identification facts.
// Record form: eventId: [short meaning, audit category, audit subcategory, outcome code, source code].
// Source M=Microsoft 2016, E=supplemental Windows Security Log Encyclopedia.
export const SECURITY_EVENTS = Object.freeze({
  1100: ["event logging service has shut down", "Other Events", "Audit System Integrity", "S", "M"],
  1101: ["Audit messages dropped during event transport", "System", "Event processing", "-", "E"],
  1102: ["audit log was cleared", "Other Events", "Audit System Integrity", "S", "M"],
  1104: ["security log is now full", "Other Events", "Audit System Integrity", "S", "M"],
  1105: ["Event log automatic backup", "Other Events", "Audit System Integrity", "S", "M"],
  1108: ["event logging service encountered an error while processing an incoming event published from %1", "Other Events", "Audit System Integrity", "S", "M"],
  4608: ["Windows is starting up", "System", "Audit Security State Change", "S", "M"],
  4609: ["Windows is shutting down", "System", "Audit Security State Change", "S", "M"],
  4610: ["An authentication package has been loaded by the Local Security Authority", "System", "Audit Security System Extension", "S", "M"],
  4611: ["A trusted logon process has been registered with the Local Security Authority", "System", "Audit Security System Extension", "S", "M"],
  4612: ["Internal resources allocated for the queuing of audit messages have been exhausted, leading to the loss of some audits", "System", "Audit System Integrity", "S", "M"],
  4614: ["A notification package has been loaded by the Security Account Manager", "System", "Audit Security System Extension", "S", "M"],
  4615: ["Invalid use of LPC port", "System", "Audit System Integrity", "S", "M"],
  4616: ["system time was changed", "System", "Audit Security State Change", "S", "M"],
  4618: ["A monitored security event pattern has occurred", "System", "Audit System Integrity", "S", "M"],
  4621: ["Administrator recovered system from CrashOnAuditFail", "System", "Audit Security State Change", "S", "M"],
  4622: ["A security package has been loaded by the Local Security Authority", "System", "Audit Security System Extension", "S", "M"],
  4624: ["An account was successfully logged on", "Logon and Logoff", "Audit Logon", "S", "M"],
  4625: ["An account failed to log on", "Logon and Logoff", "Audit Account Lockout", "F", "M"],
  4626: ["User/Device claims information", "Logon and Logoff", "Audit User/Device Claims", "S", "M"],
  4627: ["Group membership information", "Logon and Logoff", "Audit Group Membership", "S", "M"],
  4634: ["An account was logged off", "Logon and Logoff", "Audit Logoff", "S", "M"],
  4646: ["IKE DoS-prevention mode started", "Logon and Logoff", "Audit IPsec Main Mode", "-", "M"],
  4647: ["User initiated logoff", "Logon and Logoff", "Audit Logoff", "S", "M"],
  4648: ["A logon was attempted using explicit credentials", "Logon and Logoff", "Audit Logon", "S", "M"],
  4649: ["A replay attack was detected", "Logon and Logoff", "Audit Other Logon/Logoff Events", "S", "M"],
  4650: ["An IPsec Main Mode security association was established", "Logon and Logoff", "Audit IPsec Main Mode", "-", "M"],
  4651: ["An IPsec Main Mode security association was established", "Logon and Logoff", "Audit IPsec Main Mode", "-", "M"],
  4652: ["An IPsec Main Mode negotiation failed", "Logon and Logoff", "Audit IPsec Main Mode", "-", "M"],
  4653: ["An IPsec Main Mode negotiation failed", "Logon and Logoff", "Audit IPsec Main Mode", "-", "M"],
  4654: ["IPsec Quick Mode negotiation failed", "Logon and Logoff", "IPsec Quick Mode", "-", "E"],
  4655: ["An IPsec Main Mode security association ended", "Logon and Logoff", "Audit IPsec Main Mode", "-", "M"],
  4656: ["A handle to an object was requested", "Object Access", "Audit File System", "S,F", "M"],
  4657: ["A registry value was modified", "Object Access", "Audit Registry", "S", "M"],
  4658: ["handle to an object was closed", "Object Access", "Audit File System", "S", "M"],
  4659: ["Object handle requested with intent to delete", "Object Access", "File System", "-", "E"],
  4660: ["An object was deleted", "Object Access", "Audit File System", "S", "M"],
  4661: ["A handle to an object was requested", "DS Access", "Audit Directory Service Access", "S,F", "M"],
  4662: ["An operation was performed on an object", "DS Access", "Audit Directory Service Access", "S,F", "M"],
  4663: ["access an object", "Object Access", "Audit File System", "S", "M"],
  4664: ["create a hard link", "Object Access", "Audit File System", "S", "M"],
  4665: ["create an application client context", "Object Access", "Audit Application Generated", "-", "M"],
  4666: ["An application attempted an operation", "Object Access", "Audit Application Generated", "-", "M"],
  4667: ["An application client context was deleted", "Object Access", "Audit Application Generated", "-", "M"],
  4668: ["An application was initialized", "Object Access", "Audit Application Generated", "-", "M"],
  4670: ["Permissions on an object were changed", "Object Access", "Audit File System", "S", "M"],
  4671: ["An application attempted to access a blocked ordinal through the TBS", "Object Access", "Audit Other Object Access Events", "-", "M"],
  4672: ["Special privileges assigned to new logon", "Logon and Logoff", "Audit Special Logon", "S", "M"],
  4673: ["A privileged service was called", "Privilege Use", "Audit Non Sensitive Privilege Use", "S,F", "M"],
  4674: ["An operation was attempted on a privileged object", "Privilege Use", "Audit Non Sensitive Privilege Use", "S,F", "M"],
  4675: ["SIDs were filtered", "Logon and Logoff", "Audit Logon", "S", "M"],
  4688: ["A new process has been created", "Detailed Tracking", "Audit Process Creation", "S", "M"],
  4689: ["A process has exited", "Detailed Tracking", "Audit Process Termination", "S", "M"],
  4690: ["duplicate a handle to an object", "Object Access", "Audit Handle Manipulation", "S", "M"],
  4691: ["Indirect access to an object was requested", "Object Access", "Audit Other Object Access Events", "S", "M"],
  4692: ["Backup of data protection master key was attempted", "Detailed Tracking", "Audit DPAPI Activity", "S,F", "M"],
  4693: ["Recovery of data protection master key was attempted", "Detailed Tracking", "Audit DPAPI Activity", "S,F", "M"],
  4694: ["Protection of auditable protected data was attempted", "Detailed Tracking", "Audit DPAPI Activity", "S,F", "M"],
  4695: ["Unprotection of auditable protected data was attempted", "Detailed Tracking", "Audit DPAPI Activity", "S,F", "M"],
  4696: ["A primary token was assigned to process", "Detailed Tracking", "Audit Process Creation", "S", "M"],
  4697: ["A service was installed in the system", "System", "Audit Security System Extension", "S", "M"],
  4698: ["A scheduled task was created", "Object Access", "Audit Other Object Access Events", "S", "M"],
  4699: ["A scheduled task was deleted", "Object Access", "Audit Other Object Access Events", "S", "M"],
  4700: ["A scheduled task was enabled", "Object Access", "Audit Other Object Access Events", "S", "M"],
  4701: ["A scheduled task was disabled", "Object Access", "Audit Other Object Access Events", "S", "M"],
  4702: ["A scheduled task was updated", "Object Access", "Audit Other Object Access Events", "S", "M"],
  4703: ["A user right was adjusted", "Policy Change", "Audit Authorization Policy Change", "S", "M"],
  4704: ["A user right was assigned", "Policy Change", "Audit Authorization Policy Change", "S", "M"],
  4705: ["A user right was removed", "Policy Change", "Audit Authorization Policy Change", "S", "M"],
  4706: ["A new trust was created to a domain", "Policy Change", "Audit Authentication Policy Change", "S", "M"],
  4707: ["A trust to a domain was removed", "Policy Change", "Audit Authentication Policy Change", "S", "M"],
  4709: ["IPsec Services was started", "Policy Change", "Audit Filtering Platform Policy Change", "S", "M"],
  4710: ["IPsec Services was disabled", "Policy Change", "Audit Filtering Platform Policy Change", "S", "M"],
  4711: ["IPsec PAStore Engine status message (consult event parameters)", "Policy Change", "Audit Filtering Platform Policy Change", "S", "M"],
  4712: ["IPsec Services encountered a potentially serious failure", "Policy Change", "Audit Filtering Platform Policy Change", "F", "M"],
  4713: ["Kerberos policy was changed", "Policy Change", "Audit Authentication Policy Change", "S", "M"],
  4714: ["Encrypted data recovery policy was changed", "Policy Change", "Audit Other Policy Change Events", "S", "M"],
  4715: ["audit policy (SACL) on an object was changed", "Policy Change", "Audit Policy Change", "S", "M"],
  4716: ["Trusted domain information was modified", "Policy Change", "Audit Authentication Policy Change", "S", "M"],
  4717: ["System security access was granted to an account", "Policy Change", "Audit Authentication Policy Change", "S", "M"],
  4718: ["System security access was removed from an account", "Policy Change", "Audit Authentication Policy Change", "S", "M"],
  4719: ["System audit policy was changed", "Policy Change", "Audit Policy Change", "S", "M"],
  4720: ["A user account was created", "Account Management", "Audit User Account Management", "S", "M"],
  4722: ["A user account was enabled", "Account Management", "Audit User Account Management", "S", "M"],
  4723: ["change an account's password", "Account Management", "Audit User Account Management", "S,F", "M"],
  4724: ["reset an account's password", "Account Management", "Audit User Account Management", "S,F", "M"],
  4725: ["A user account was disabled", "Account Management", "Audit User Account Management", "S", "M"],
  4726: ["A user account was deleted", "Account Management", "Audit User Account Management", "S", "M"],
  4727: ["A security-enabled global group was created", "Account Management", "Audit Security Group Management", "S", "M"],
  4728: ["A member was added to a security-enabled global group", "Account Management", "Audit Security Group Management", "S", "M"],
  4729: ["A member was removed from a security-enabled global group", "Account Management", "Audit Security Group Management", "S", "M"],
  4730: ["A security-enabled global group was deleted", "Account Management", "Audit Security Group Management", "S", "M"],
  4731: ["A security-enabled local group was created", "Account Management", "Audit Security Group Management", "S", "M"],
  4732: ["A member was added to a security-enabled local group", "Account Management", "Audit Security Group Management", "S", "M"],
  4733: ["A member was removed from a security-enabled local group", "Account Management", "Audit Security Group Management", "S", "M"],
  4734: ["A security-enabled local group was deleted", "Account Management", "Audit Security Group Management", "S", "M"],
  4735: ["A security-enabled local group was changed", "Account Management", "Audit Security Group Management", "S", "M"],
  4737: ["A security-enabled global group was changed", "Account Management", "Audit Security Group Management", "S", "M"],
  4738: ["A user account was changed", "Account Management", "Audit User Account Management", "S", "M"],
  4739: ["Domain Policy was changed", "Policy Change", "Audit Authentication Policy Change", "S", "M"],
  4740: ["A user account was locked out", "Account Management", "Audit User Account Management", "S", "M"],
  4741: ["A computer account was created", "Account Management", "Audit Computer Account Management", "S", "M"],
  4742: ["A computer account was changed", "Account Management", "Audit Computer Account Management", "S", "M"],
  4743: ["A computer account was deleted", "Account Management", "Audit Computer Account Management", "S", "M"],
  4744: ["A security-disabled local group was created", "Account Management", "Audit Distribution Group Management", "S", "M"],
  4745: ["A security-disabled local group was changed", "Account Management", "Audit Distribution Group Management", "S", "M"],
  4746: ["A member was added to a security-disabled local group", "Account Management", "Audit Distribution Group Management", "S", "M"],
  4747: ["A member was removed from a security-disabled local group", "Account Management", "Audit Distribution Group Management", "S", "M"],
  4748: ["A security-disabled local group was deleted", "Account Management", "Audit Distribution Group Management", "S", "M"],
  4749: ["A security-disabled global group was created", "Account Management", "Audit Distribution Group Management", "S", "M"],
  4750: ["A security-disabled global group was changed", "Account Management", "Audit Distribution Group Management", "S", "M"],
  4751: ["A member was added to a security-disabled global group", "Account Management", "Audit Distribution Group Management", "S", "M"],
  4752: ["A member was removed from a security-disabled global group", "Account Management", "Audit Distribution Group Management", "S", "M"],
  4753: ["A security-disabled global group was deleted", "Account Management", "Audit Distribution Group Management", "S", "M"],
  4754: ["A security-enabled universal group was created", "Account Management", "Audit Security Group Management", "S", "M"],
  4755: ["A security-enabled universal group was changed", "Account Management", "Audit Security Group Management", "S", "M"],
  4756: ["A member was added to a security-enabled universal group", "Account Management", "Audit Security Group Management", "S", "M"],
  4757: ["A member was removed from a security-enabled universal group", "Account Management", "Audit Security Group Management", "S", "M"],
  4758: ["A security-enabled universal group was deleted", "Account Management", "Audit Security Group Management", "S", "M"],
  4759: ["A security-disabled universal group was created", "Account Management", "Audit Distribution Group Management", "S", "M"],
  4760: ["A security-disabled universal group was changed", "Account Management", "Audit Distribution Group Management", "S", "M"],
  4761: ["A member was added to a security-disabled universal group", "Account Management", "Audit Distribution Group Management", "S", "M"],
  4762: ["A member was removed from a security-disabled universal group", "Account Management", "Audit Distribution Group Management", "S", "M"],
  4763: ["A security-disabled universal group was deleted", "Account Management", "Audit Distribution Group Management", "S", "M"],
  4764: ["A group’s type was changed", "Account Management", "Audit Security Group Management", "S", "M"],
  4765: ["SID History was added to an account", "Account Management", "Audit User Account Management", "S", "M"],
  4766: ["An attempt to add SID History to an account failed", "Account Management", "Audit User Account Management", "F", "M"],
  4767: ["A user account was unlocked", "Account Management", "Audit User Account Management", "S", "M"],
  4768: ["A Kerberos authentication ticket (TGT) was requested", "Account Logon", "Audit Kerberos Authentication Service", "S,F", "M"],
  4769: ["A Kerberos service ticket was requested", "Account Logon", "Audit Kerberos Service Ticket Operations", "S,F", "M"],
  4770: ["A Kerberos service ticket was renewed", "Account Logon", "Audit Kerberos Service Ticket Operations", "S", "M"],
  4771: ["Kerberos pre-authentication failed", "Account Logon", "Audit Kerberos Authentication Service", "F", "M"],
  4772: ["A Kerberos authentication ticket request failed", "Account Logon", "Audit Kerberos Authentication Service", "F", "M"],
  4773: ["A Kerberos service ticket request failed", "Account Logon", "Audit Kerberos Service Ticket Operations", "F", "M"],
  4774: ["An account was mapped for logon", "Account Logon", "Audit Credential Validation", "S", "M"],
  4775: ["An account could not be mapped for logon", "Account Logon", "Audit Credential Validation", "F", "M"],
  4776: ["computer attempted to validate the credentials for an account", "Account Logon", "Audit Credential Validation", "S,F", "M"],
  4777: ["domain controller failed to validate the credentials for an account", "Account Logon", "Audit Credential Validation", "F", "M"],
  4778: ["A session was reconnected to a Window Station", "Logon and Logoff", "Audit Other Logon/Logoff Events", "S", "M"],
  4779: ["A session was disconnected from a Window Station", "Logon and Logoff", "Audit Other Logon/Logoff Events", "S", "M"],
  4780: ["ACL was set on accounts which are members of administrators groups", "Account Management", "Audit User Account Management", "S", "M"],
  4781: ["name of an account was changed", "Account Management", "Audit User Account Management", "S", "M"],
  4782: ["Password hash of an account was accessed", "Account Management", "Audit Other Account Management Events", "S", "M"],
  4783: ["A basic application group was created", "Account Management", "Audit Application Group Management", "S", "M"],
  4784: ["A basic application group was changed", "Account Management", "Audit Application Group Management", "S", "M"],
  4785: ["A member was added to a basic application group", "Account Management", "Audit Application Group Management", "S", "M"],
  4786: ["A member was removed from a basic application group", "Account Management", "Audit Application Group Management", "S", "M"],
  4787: ["A non-member was added to a basic application group", "Account Management", "Audit Application Group Management", "S", "M"],
  4788: ["A non-member was removed from a basic application group", "Account Management", "Audit Application Group Management", "S", "M"],
  4789: ["A basic application group was deleted", "Account Management", "Audit Application Group Management", "S", "M"],
  4790: ["An LDAP query group was created", "Account Management", "Audit Application Group Management", "S", "M"],
  4791: ["LDAP query group changed", "Account Management", "Audit Application Group Management", "S", "M"],
  4792: ["An LDAP query group was deleted", "Account Management", "Audit Application Group Management", "S", "M"],
  4793: ["Password Policy Checking API was called", "Account Management", "Audit Other Account Management Events", "S", "M"],
  4794: ["set the Directory Services Restore Mode administrator password", "Account Management", "Audit User Account Management", "S,F", "M"],
  4797: ["Account queried for a blank password", "Account Management", "User Account Management", "-", "E"],
  4798: ["A user's local group membership was enumerated", "Account Management", "Audit User Account Management", "S", "M"],
  4799: ["A security-enabled local group membership was enumerated", "Account Management", "Audit Security Group Management", "S", "M"],
  4800: ["workstation was locked", "Logon and Logoff", "Audit Other Logon/Logoff Events", "S", "M"],
  4801: ["workstation was unlocked", "Logon and Logoff", "Audit Other Logon/Logoff Events", "S", "M"],
  4802: ["screen saver was invoked", "Logon and Logoff", "Audit Other Logon/Logoff Events", "S", "M"],
  4803: ["screen saver was dismissed", "Logon and Logoff", "Audit Other Logon/Logoff Events", "S", "M"],
  4816: ["RPC detected an integrity violation while decrypting an incoming message", "System", "Audit System Integrity", "S", "M"],
  4817: ["Auditing settings on object were changed", "Policy Change", "Audit Policy Change", "S", "M"],
  4818: ["Proposed Central Access Policy does not grant the same access permissions as the current Central Access Policy", "Object Access", "Audit Central Policy Staging", "S", "M"],
  4819: ["Central Access Policies on the machine have been changed", "Policy Change", "Audit Other Policy Change Events", "S", "M"],
  4820: ["Kerberos TGT denied by device access restrictions", "Account Logon", "Kerberos Authentication Service", "-", "E"],
  4821: ["Kerberos service ticket denied by access restrictions", "System", "Other System Events", "-", "E"],
  4822: ["NTLM authentication rejected for Protected Users membership", "System", "Other System Events", "-", "E"],
  4823: ["NTLM authentication denied by access restrictions", "System", "Other System Events", "-", "E"],
  4824: ["DES/RC4 Kerberos preauthentication rejected for Protected Users account", "System", "Other System Events", "-", "E"],
  4825: ["Remote Desktop access denied for account", "System", "Other System Events", "-", "E"],
  4826: ["Boot Configuration Data loaded", "Policy Change", "Audit Other Policy Change Events", "S", "M"],
  4830: ["SID history removed from account", "System", "Other System Events", "-", "E"],
  4864: ["A namespace collision was detected", "Policy Change", "Audit Authentication Policy Change", "S", "M"],
  4865: ["A trusted forest information entry was added", "Policy Change", "Audit Authentication Policy Change", "S", "M"],
  4866: ["A trusted forest information entry was removed", "Policy Change", "Audit Authentication Policy Change", "S", "M"],
  4867: ["A trusted forest information entry was modified", "Policy Change", "Audit Authentication Policy Change", "S", "M"],
  4868: ["certificate manager denied a pending certificate request", "Object Access", "Audit Certification Services", "-", "M"],
  4869: ["Certificate Services received a resubmitted certificate request", "Object Access", "Audit Certification Services", "-", "M"],
  4870: ["Certificate Services revoked a certificate", "Object Access", "Audit Certification Services", "-", "M"],
  4871: ["Certificate Services received a request to publish the certificate revocation list (CRL)", "Object Access", "Audit Certification Services", "-", "M"],
  4872: ["Certificate Services published the certificate revocation list (CRL)", "Object Access", "Audit Certification Services", "-", "M"],
  4873: ["A certificate request extension changed", "Object Access", "Audit Certification Services", "-", "M"],
  4874: ["One or more certificate request attributes changed", "Object Access", "Audit Certification Services", "-", "M"],
  4875: ["Certificate Services received a request to shut down", "Object Access", "Audit Certification Services", "-", "M"],
  4876: ["Certificate Services backup started", "Object Access", "Audit Certification Services", "-", "M"],
  4877: ["Certificate Services backup completed", "Object Access", "Audit Certification Services", "-", "M"],
  4878: ["Certificate Services restore started", "Object Access", "Audit Certification Services", "-", "M"],
  4879: ["Certificate Services restore completed", "Object Access", "Audit Certification Services", "-", "M"],
  4880: ["Certificate Services started", "Object Access", "Audit Certification Services", "-", "M"],
  4881: ["Certificate Services stopped", "Object Access", "Audit Certification Services", "-", "M"],
  4882: ["security permissions for Certificate Services changed", "Object Access", "Audit Certification Services", "-", "M"],
  4883: ["Certificate Services retrieved an archived key", "Object Access", "Audit Certification Services", "-", "M"],
  4884: ["Certificate Services imported a certificate into its database", "Object Access", "Audit Certification Services", "-", "M"],
  4885: ["audit filter for Certificate Services changed", "Object Access", "Audit Certification Services", "-", "M"],
  4886: ["Certificate Services received a certificate request", "Object Access", "Audit Certification Services", "-", "M"],
  4887: ["Certificate Services approved a certificate request and issued a certificate", "Object Access", "Audit Certification Services", "-", "M"],
  4888: ["Certificate Services denied a certificate request", "Object Access", "Audit Certification Services", "-", "M"],
  4889: ["Certificate Services set the status of a certificate request to pending", "Object Access", "Audit Certification Services", "-", "M"],
  4890: ["certificate manager settings for Certificate Services changed", "Object Access", "Audit Certification Services", "-", "M"],
  4891: ["A configuration entry changed in Certificate Services", "Object Access", "Audit Certification Services", "-", "M"],
  4892: ["A property of Certificate Services changed", "Object Access", "Audit Certification Services", "-", "M"],
  4893: ["Certificate Services archived a key", "Object Access", "Audit Certification Services", "-", "M"],
  4894: ["Certificate Services imported and archived a key", "Object Access", "Audit Certification Services", "-", "M"],
  4895: ["Certificate Services published the CA certificate to Active Directory Domain Services", "Object Access", "Audit Certification Services", "-", "M"],
  4896: ["One or more rows have been deleted from the certificate database", "Object Access", "Audit Certification Services", "-", "M"],
  4897: ["Role separation enabled", "Object Access", "Audit Certification Services", "-", "M"],
  4898: ["Certificate Services loaded a template", "Object Access", "Audit Certification Services", "-", "M"],
  4899: ["Certificate Services template updated", "Object Access", "Certification Services", "-", "E"],
  4900: ["Certificate Services template security updated", "Object Access", "Certification Services", "-", "E"],
  4902: ["Per-user audit policy table was created", "Policy Change", "Audit Policy Change", "S", "M"],
  4904: ["register a security event source", "Policy Change", "Audit Policy Change", "S", "M"],
  4905: ["unregister a security event source", "Policy Change", "Audit Policy Change", "S", "M"],
  4906: ["CrashOnAuditFail value has changed", "Policy Change", "Audit Policy Change", "S", "M"],
  4907: ["Auditing settings on object were changed", "Policy Change", "Audit Policy Change", "S", "M"],
  4908: ["Special Groups Logon table modified", "Policy Change", "Audit Policy Change", "S", "M"],
  4909: ["local policy settings for the TBS were changed", "Policy Change", "Audit Other Policy Change Events", "-", "M"],
  4910: ["group policy settings for the TBS were changed", "Policy Change", "Audit Other Policy Change Events", "-", "M"],
  4911: ["Resource attributes of the object were changed", "Policy Change", "Audit Authorization Policy Change", "S", "M"],
  4912: ["Per User Audit Policy was changed", "Policy Change", "Audit Policy Change", "S", "M"],
  4913: ["Central Access Policy on the object was changed", "Policy Change", "Audit Authorization Policy Change", "S", "M"],
  4928: ["An Active Directory replica source naming context was established", "DS Access", "Audit Detailed Directory Service Replication", "S,F", "M"],
  4929: ["An Active Directory replica source naming context was removed", "DS Access", "Audit Detailed Directory Service Replication", "S,F", "M"],
  4930: ["An Active Directory replica source naming context was modified", "DS Access", "Audit Detailed Directory Service Replication", "S,F", "M"],
  4931: ["An Active Directory replica destination naming context was modified", "DS Access", "Audit Detailed Directory Service Replication", "S,F", "M"],
  4932: ["Synchronization of a replica of an Active Directory naming context has begun", "DS Access", "Audit Directory Service Replication", "S", "M"],
  4933: ["Synchronization of a replica of an Active Directory naming context has ended", "DS Access", "Audit Directory Service Replication", "S,F", "M"],
  4934: ["Attributes of an Active Directory object were replicated", "DS Access", "Audit Detailed Directory Service Replication", "S", "M"],
  4935: ["Replication failure begins", "DS Access", "Audit Detailed Directory Service Replication", "F", "M"],
  4936: ["Replication failure ends", "DS Access", "Audit Detailed Directory Service Replication", "S", "M"],
  4937: ["A lingering object was removed from a replica", "DS Access", "Audit Detailed Directory Service Replication", "S", "M"],
  4944: ["following policy was active when the Windows Firewall started", "Policy Change", "Audit MPSSVC Rule-Level Policy Change", "S", "M"],
  4945: ["A rule was listed when the Windows Firewall started", "Policy Change", "Audit MPSSVC Rule-Level Policy Change", "S", "M"],
  4946: ["A change has been made to Windows Firewall exception list", "Policy Change", "Audit MPSSVC Rule-Level Policy Change", "S", "M"],
  4947: ["A change has been made to Windows Firewall exception list", "Policy Change", "Audit MPSSVC Rule-Level Policy Change", "S", "M"],
  4948: ["A change has been made to Windows Firewall exception list", "Policy Change", "Audit MPSSVC Rule-Level Policy Change", "S", "M"],
  4949: ["Windows Firewall settings were restored to the default values", "Policy Change", "Audit MPSSVC Rule-Level Policy Change", "S", "M"],
  4950: ["A Windows Firewall setting has changed", "Policy Change", "Audit MPSSVC Rule-Level Policy Change", "S", "M"],
  4951: ["A rule has been ignored because its major version number was not recognized by Windows Firewall", "Policy Change", "Audit MPSSVC Rule-Level Policy Change", "F", "M"],
  4952: ["Parts of a rule have been ignored because its minor version number was not recognized by Windows Firewall", "Policy Change", "Audit MPSSVC Rule-Level Policy Change", "F", "M"],
  4953: ["Windows Firewall ignored a rule because it could not be parsed", "Policy Change", "Audit MPSSVC Rule-Level Policy Change", "F", "M"],
  4954: ["Windows Firewall Group Policy settings have changed", "Policy Change", "Audit MPSSVC Rule-Level Policy Change", "S", "M"],
  4956: ["Windows Firewall has changed the active profile", "Policy Change", "Audit MPSSVC Rule-Level Policy Change", "S", "M"],
  4957: ["Windows Firewall did not apply the following rule", "Policy Change", "Audit MPSSVC Rule-Level Policy Change", "F", "M"],
  4958: ["Windows Firewall did not apply the following rule because the rule referred to items not configured on this computer", "Policy Change", "Audit MPSSVC Rule-Level Policy Change", "F", "M"],
  4960: ["IPsec dropped an inbound packet that failed an integrity check", "System", "Audit IPsec Driver", "S", "M"],
  4961: ["IPsec dropped an inbound packet that failed a replay check", "System", "Audit IPsec Driver", "S", "M"],
  4962: ["IPsec dropped an inbound packet that failed a replay check", "System", "Audit IPsec Driver", "S", "M"],
  4963: ["IPsec dropped an inbound clear text packet that should have been secured", "System", "Audit IPsec Driver", "S", "M"],
  4964: ["Special groups have been assigned to a new logon", "Logon and Logoff", "Audit Special Logon", "S", "M"],
  4965: ["IPsec received a packet from a remote computer with an incorrect Security Parameter Index (SPI)", "System", "Audit IPsec Driver", "S", "M"],
  4976: ["During Main Mode negotiation, IPsec received an invalid negotiation packet", "Logon and Logoff", "Audit IPsec Main Mode", "-", "M"],
  4977: ["During Quick Mode negotiation, IPsec received an invalid negotiation packet", "Logon and Logoff", "Audit IPsec Quick Mode", "-", "M"],
  4978: ["During Extended Mode negotiation, IPsec received an invalid negotiation packet", "Logon and Logoff", "Audit IPsec Extended Mode", "-", "M"],
  4979: ["IPsec Main Mode and Extended Mode security associations were established", "Logon and Logoff", "Audit IPsec Extended Mode", "-", "M"],
  4980: ["IPsec Main Mode and Extended Mode security associations were established", "Logon and Logoff", "Audit IPsec Extended Mode", "-", "M"],
  4981: ["IPsec Main Mode and Extended Mode security associations were established", "Logon and Logoff", "Audit IPsec Extended Mode", "-", "M"],
  4982: ["IPsec Main Mode and Extended Mode security associations were established", "Logon and Logoff", "Audit IPsec Extended Mode", "-", "M"],
  4983: ["An IPsec Extended Mode negotiation failed", "Logon and Logoff", "Audit IPsec Extended Mode", "-", "M"],
  4984: ["An IPsec Extended Mode negotiation failed", "Logon and Logoff", "Audit IPsec Extended Mode", "-", "M"],
  4985: ["state of a transaction has changed", "Object Access", "Audit File System", "S", "M"],
  5024: ["Windows Firewall Service has started successfully", "System", "Audit Other System Events", "S", "M"],
  5025: ["Windows Firewall Service has been stopped", "System", "Audit Other System Events", "S", "M"],
  5027: ["Windows Firewall Service was unable to retrieve the security policy from the local storage", "System", "Audit Other System Events", "F", "M"],
  5028: ["Windows Firewall Service was unable to parse the new security policy", "System", "Audit Other System Events", "F", "M"],
  5029: ["Windows Firewall Service failed to initialize the driver", "System", "Audit Other System Events", "F", "M"],
  5030: ["Windows Firewall Service failed to start", "System", "Audit Other System Events", "F", "M"],
  5031: ["Windows Firewall Service blocked an application from accepting incoming connections on the network", "Object Access", "Audit Filtering Platform Connection", "F", "M"],
  5032: ["Windows Firewall was unable to notify the user that it blocked an application from accepting incoming connections on the network", "System", "Audit Other System Events", "F", "M"],
  5033: ["Windows Firewall Driver has started successfully", "System", "Audit Other System Events", "S", "M"],
  5034: ["Windows Firewall Driver was stopped", "System", "Audit Other System Events", "S", "M"],
  5035: ["Windows Firewall Driver failed to start", "System", "Audit Other System Events", "F", "M"],
  5037: ["Windows Firewall Driver detected critical runtime error", "System", "Audit Other System Events", "F", "M"],
  5038: ["Code integrity determined that the image hash of a file is not valid", "System", "Audit System Integrity", "F", "M"],
  5039: ["A registry key was virtualized", "Object Access", "Audit Registry", "-", "M"],
  5040: ["A change has been made to IPsec settings", "Policy Change", "Audit Filtering Platform Policy Change", "S", "M"],
  5041: ["A change has been made to IPsec settings", "Policy Change", "Audit Filtering Platform Policy Change", "S", "M"],
  5042: ["A change has been made to IPsec settings", "Policy Change", "Audit Filtering Platform Policy Change", "S", "M"],
  5043: ["A change has been made to IPsec settings", "Policy Change", "Audit Filtering Platform Policy Change", "S", "M"],
  5044: ["A change has been made to IPsec settings", "Policy Change", "Audit Filtering Platform Policy Change", "S", "M"],
  5045: ["A change has been made to IPsec settings", "Policy Change", "Audit Filtering Platform Policy Change", "S", "M"],
  5046: ["A change has been made to IPsec settings", "Policy Change", "Audit Filtering Platform Policy Change", "S", "M"],
  5047: ["A change has been made to IPsec settings", "Policy Change", "Audit Filtering Platform Policy Change", "S", "M"],
  5048: ["A change has been made to IPsec settings", "Policy Change", "Audit Filtering Platform Policy Change", "S", "M"],
  5049: ["An IPsec Security Association was deleted", "Logon and Logoff", "Audit IPsec Main Mode", "-", "M"],
  5050: ["Programmatic Windows Firewall disable attempt", "System", "Other System Events", "-", "E"],
  5051: ["A file was virtualized", "Object Access", "Audit File System", "-", "M"],
  5056: ["A cryptographic self-test was performed", "System", "Audit System Integrity", "S", "M"],
  5057: ["A cryptographic primitive operation failed", "System", "Audit System Integrity", "F", "M"],
  5058: ["Key file operation", "System", "Audit Other System Events", "S,F", "M"],
  5059: ["Key migration operation", "System", "Audit Other System Events", "S,F", "M"],
  5060: ["Verification operation failed", "System", "Audit System Integrity", "F", "M"],
  5061: ["Cryptographic operation", "System", "Audit System Integrity", "S,F", "M"],
  5062: ["A kernel-mode cryptographic self-test was performed", "System", "Audit System Integrity", "S", "M"],
  5063: ["A cryptographic provider operation was attempted", "Policy Change", "Audit Other Policy Change Events", "S,F", "M"],
  5064: ["A cryptographic context operation was attempted", "Policy Change", "Audit Other Policy Change Events", "S,F", "M"],
  5065: ["A cryptographic context modification was attempted", "Policy Change", "Audit Other Policy Change Events", "S,F", "M"],
  5066: ["A cryptographic function operation was attempted", "Policy Change", "Audit Other Policy Change Events", "S,F", "M"],
  5067: ["A cryptographic function modification was attempted", "Policy Change", "Audit Other Policy Change Events", "S,F", "M"],
  5068: ["A cryptographic function provider operation was attempted", "Policy Change", "Audit Other Policy Change Events", "S,F", "M"],
  5069: ["A cryptographic function property operation was attempted", "Policy Change", "Audit Other Policy Change Events", "S,F", "M"],
  5070: ["A cryptographic function property modification was attempted", "Policy Change", "Audit Other Policy Change Events", "S,F", "M"],
  5071: ["Microsoft key distribution service denied key access", "Policy Change", "Other Policy Change Events", "-", "E"],
  5120: ["Online Certificate Status Protocol responder service started", "Object Access", "Certification Services", "-", "E"],
  5121: ["Online Certificate Status Protocol responder service stopped", "Object Access", "Certification Services", "-", "E"],
  5122: ["OCSP responder service configuration entry changed", "Object Access", "Certification Services", "-", "E"],
  5123: ["OCSP responder service configuration entry changed", "Object Access", "Certification Services", "-", "E"],
  5124: ["OCSP responder service security settings updated", "Object Access", "Certification Services", "-", "E"],
  5125: ["OCSP responder service request submitted", "Object Access", "Certification Services", "-", "E"],
  5126: ["OCSP responder signing certificate automatically updated", "Object Access", "Certification Services", "-", "E"],
  5127: ["OCSP revocation provider information updated", "Object Access", "Certification Services", "-", "E"],
  5136: ["A directory service object was modified", "DS Access", "Audit Directory Service Changes", "S", "M"],
  5137: ["A directory service object was created", "DS Access", "Audit Directory Service Changes", "S", "M"],
  5138: ["A directory service object was undeleted", "DS Access", "Audit Directory Service Changes", "S", "M"],
  5139: ["A directory service object was moved", "DS Access", "Audit Directory Service Changes", "S", "M"],
  5140: ["A network share object was accessed", "Object Access", "Audit File Share", "S,F", "M"],
  5141: ["A directory service object was deleted", "DS Access", "Audit Directory Service Changes", "S", "M"],
  5142: ["A network share object was added", "Object Access", "Audit File Share", "S", "M"],
  5143: ["A network share object was modified", "Object Access", "Audit File Share", "S", "M"],
  5144: ["A network share object was deleted", "Object Access", "Audit File Share", "S", "M"],
  5145: ["A network share object was checked to see whether client can be granted desired access", "Object Access", "Audit Detailed File Share", "S,F", "M"],
  5146: ["Windows Filtering Platform blocked packet", "Object Access", "Filtering Platform", "-", "E"],
  5147: ["More restrictive WFP filter blocked packet", "Object Access", "Filtering Platform", "-", "E"],
  5148: ["Windows Filtering Platform has detected a DoS attack and entered a defensive mode; packets associated with this attack will be discarded", "Object Access", "Audit Other Object Access Events", "F", "M"],
  5149: ["DoS attack has subsided and normal processing is being resumed", "Object Access", "Audit Other Object Access Events", "F", "M"],
  5150: ["Windows Filtering Platform blocked a packet", "Object Access", "Audit Filtering Platform Connection", "-", "M"],
  5151: ["A more restrictive Windows Filtering Platform filter has blocked a packet", "Object Access", "Audit Filtering Platform Connection", "-", "M"],
  5152: ["Windows Filtering Platform blocked a packet", "Object Access", "Audit Filtering Platform Packet Drop", "F", "M"],
  5153: ["A more restrictive Windows Filtering Platform filter has blocked a packet", "Object Access", "Audit Filtering Platform Packet Drop", "S", "M"],
  5154: ["Windows Filtering Platform has permitted an application or service to listen on a port for incoming connections", "Object Access", "Audit Filtering Platform Connection", "S", "M"],
  5155: ["Windows Filtering Platform has blocked an application or service from listening on a port for incoming connections", "Object Access", "Audit Filtering Platform Connection", "F", "M"],
  5156: ["Windows Filtering Platform has permitted a connection", "Object Access", "Audit Filtering Platform Connection", "S", "M"],
  5157: ["Windows Filtering Platform has blocked a connection", "Object Access", "Audit Filtering Platform Connection", "F", "M"],
  5158: ["Windows Filtering Platform has permitted a bind to a local port", "Object Access", "Audit Filtering Platform Connection", "S", "M"],
  5159: ["Windows Filtering Platform has blocked a bind to a local port", "Object Access", "Audit Filtering Platform Connection", "F", "M"],
  5168: ["SPN check for SMB/SMB2 failed", "Object Access", "Audit File Share", "F", "M"],
  5169: ["Directory service object modified", "DS Access", "Directory Service Changes", "-", "E"],
  5170: ["Directory service object modified during background cleanup", "DS Access", "Directory Service Changes", "-", "E"],
  5376: ["Credential Manager credentials were backed up", "Account Management", "Audit User Account Management", "S", "M"],
  5377: ["Credential Manager credentials were restored from a backup", "Account Management", "Audit User Account Management", "S", "M"],
  5378: ["requested credentials delegation was disallowed by policy", "Logon and Logoff", "Audit Other Logon/Logoff Events", "F", "M"],
  5379: ["Credential Manager credentials accessed", "Account Management", "Credential Manager", "-", "E"],
  5380: ["Windows Vault credential lookup", "Account Management", "Credential Manager", "-", "E"],
  5381: ["Windows Vault credentials accessed", "Account Management", "Credential Manager", "-", "E"],
  5382: ["Windows Vault credentials accessed", "Account Management", "Credential Manager", "-", "E"],
  5440: ["following callout was present when the Windows Filtering Platform Base Filtering Engine started", "Policy Change", "Audit Filtering Platform Policy Change", "S", "M"],
  5441: ["following filter was present when the Windows Filtering Platform Base Filtering Engine started", "Policy Change", "Audit Filtering Platform Policy Change", "S", "M"],
  5442: ["following provider was present when the Windows Filtering Platform Base Filtering Engine started", "Policy Change", "Audit Filtering Platform Policy Change", "S", "M"],
  5443: ["following provider context was present when the Windows Filtering Platform Base Filtering Engine started", "Policy Change", "Audit Filtering Platform Policy Change", "S", "M"],
  5444: ["following sub-layer was present when the Windows Filtering Platform Base Filtering Engine started", "Policy Change", "Audit Filtering Platform Policy Change", "S", "M"],
  5446: ["A Windows Filtering Platform callout has been changed", "Policy Change", "Audit Filtering Platform Policy Change", "S", "M"],
  5447: ["A Windows Filtering Platform filter has been changed", "Policy Change", "Audit Other Policy Change Events", "S", "M"],
  5448: ["A Windows Filtering Platform provider has been changed", "Policy Change", "Audit Filtering Platform Policy Change", "S", "M"],
  5449: ["A Windows Filtering Platform provider context has been changed", "Policy Change", "Audit Filtering Platform Policy Change", "S", "M"],
  5450: ["A Windows Filtering Platform sub-layer has been changed", "Policy Change", "Audit Filtering Platform Policy Change", "S", "M"],
  5451: ["An IPsec Quick Mode security association was established", "Logon and Logoff", "Audit IPsec Quick Mode", "-", "M"],
  5452: ["An IPsec Quick Mode security association ended", "Logon and Logoff", "Audit IPsec Quick Mode", "-", "M"],
  5453: ["An IPsec negotiation with a remote computer failed because the IKE and AuthIP IPsec Keying Modules (IKEEXT) service is not started", "Logon and Logoff", "Audit IPsec Main Mode", "-", "M"],
  5456: ["PAStore Engine applied Active Directory storage IPsec policy on the computer", "Policy Change", "Audit Filtering Platform Policy Change", "S", "M"],
  5457: ["PAStore Engine failed to apply Active Directory storage IPsec policy on the computer", "Policy Change", "Audit Filtering Platform Policy Change", "F", "M"],
  5458: ["PAStore Engine applied locally cached copy of Active Directory storage IPsec policy on the computer", "Policy Change", "Audit Filtering Platform Policy Change", "S", "M"],
  5459: ["PAStore Engine failed to apply locally cached copy of Active Directory storage IPsec policy on the computer", "Policy Change", "Audit Filtering Platform Policy Change", "F", "M"],
  5460: ["PAStore Engine applied local registry storage IPsec policy on the computer", "Policy Change", "Audit Filtering Platform Policy Change", "S", "M"],
  5461: ["PAStore Engine failed to apply local registry storage IPsec policy on the computer", "Policy Change", "Audit Filtering Platform Policy Change", "F", "M"],
  5462: ["PAStore Engine failed to apply some rules of the active IPsec policy on the computer", "Policy Change", "Audit Filtering Platform Policy Change", "F", "M"],
  5463: ["PAStore Engine polled for changes to the active IPsec policy and detected no changes", "Policy Change", "Audit Filtering Platform Policy Change", "S", "M"],
  5464: ["PAStore Engine polled for changes to the active IPsec policy, detected changes, and applied them to IPsec Services", "Policy Change", "Audit Filtering Platform Policy Change", "S", "M"],
  5465: ["PAStore Engine received a control for forced reloading of IPsec policy and processed the control successfully", "Policy Change", "Audit Filtering Platform Policy Change", "S", "M"],
  5466: ["PAStore Engine polled for changes to the Active Directory IPsec policy, determined that Active Directory cannot be reached, and will use the cached copy of the Active Directory IPsec policy instead", "Policy Change", "Audit Filtering Platform Policy Change", "F", "M"],
  5467: ["PAStore Engine polled for changes to the Active Directory IPsec policy, determined that Active Directory can be reached, and found no changes to the policy", "Policy Change", "Audit Filtering Platform Policy Change", "F", "M"],
  5468: ["PAStore Engine polled for changes to the Active Directory IPsec policy, determined that Active Directory can be reached, found changes to the policy, and applied those changes", "Policy Change", "Audit Filtering Platform Policy Change", "S", "M"],
  5471: ["PAStore Engine loaded local storage IPsec policy on the computer", "Policy Change", "Audit Filtering Platform Policy Change", "S", "M"],
  5472: ["PAStore Engine failed to load local storage IPsec policy on the computer", "Policy Change", "Audit Filtering Platform Policy Change", "F", "M"],
  5473: ["PAStore Engine loaded directory storage IPsec policy on the computer", "Policy Change", "Audit Filtering Platform Policy Change", "S", "M"],
  5474: ["PAStore Engine failed to load directory storage IPsec policy on the computer", "Policy Change", "Audit Filtering Platform Policy Change", "F", "M"],
  5477: ["PAStore Engine failed to add quick mode filter", "Policy Change", "Audit Filtering Platform Policy Change", "F", "M"],
  5478: ["IPsec Services has started successfully", "System", "Audit IPsec Driver", "S", "M"],
  5479: ["IPsec Services has been shut down successfully", "System", "Audit IPsec Driver", "-", "M"],
  5480: ["IPsec Services failed to get the complete list of network interfaces on the computer", "System", "Audit IPsec Driver", "F", "M"],
  5483: ["IPsec Services failed to initialize RPC server", "System", "Audit IPsec Driver", "F", "M"],
  5484: ["IPsec Services has experienced a critical failure and has been shut down", "System", "Audit IPsec Driver", "F", "M"],
  5485: ["IPsec Services failed to process some IPsec filters on a plug-and-play event for network interfaces", "System", "Audit IPsec Driver", "F", "M"],
  5632: ["A request was made to authenticate to a wireless network", "Logon and Logoff", "Audit Other Logon/Logoff Events", "S,F", "M"],
  5633: ["A request was made to authenticate to a wired network", "Logon and Logoff", "Audit Other Logon/Logoff Events", "S,F", "M"],
  5712: ["A Remote Procedure Call (RPC) was attempted", "Detailed Tracking", "Audit RPC Events", "S", "M"],
  5888: ["An object in the COM+ Catalog was modified", "Object Access", "Audit Other Object Access Events", "S", "M"],
  5889: ["An object was deleted from the COM+ Catalog", "Object Access", "Audit Other Object Access Events", "S", "M"],
  5890: ["An object was added to the COM+ Catalog", "Object Access", "Audit Other Object Access Events", "S", "M"],
  6144: ["Security policy in the group policy objects has been applied successfully", "Policy Change", "Audit Other Policy Change Events", "S", "M"],
  6145: ["One or more errors occurred while processing security policy in the group policy objects", "Policy Change", "Audit Other Policy Change Events", "F", "M"],
  6272: ["Network Policy Server granted access to a user", "Logon and Logoff", "Audit Network Policy Server", "-", "M"],
  6273: ["Network Policy Server denied access to a user", "Logon and Logoff", "Audit Network Policy Server", "-", "M"],
  6274: ["Network Policy Server discarded the request for a user", "Logon and Logoff", "Audit Network Policy Server", "-", "M"],
  6275: ["Network Policy Server discarded the accounting request for a user", "Logon and Logoff", "Audit Network Policy Server", "-", "M"],
  6276: ["Network Policy Server quarantined a user", "Logon and Logoff", "Audit Network Policy Server", "-", "M"],
  6277: ["Network Policy Server granted access to a user but put it on probation because the host did not meet the defined health policy", "Logon and Logoff", "Audit Network Policy Server", "-", "M"],
  6278: ["Network Policy Server granted full access to a user because the host met the defined health policy", "Logon and Logoff", "Audit Network Policy Server", "-", "M"],
  6279: ["Network Policy Server locked the user account due to repeated failed authentication attempts", "Logon and Logoff", "Audit Network Policy Server", "-", "M"],
  6280: ["Network Policy Server unlocked the user account", "Logon and Logoff", "Audit Network Policy Server", "-", "M"],
  6281: ["Code Integrity determined that the page hashes of an image file are not valid", "System", "Audit System Integrity", "F", "M"],
  6400: ["BranchCache: Received an incorrectly formatted response while discovering availability of content", "System", "Audit Other System Events", "-", "M"],
  6401: ["BranchCache: Received invalid data from a peer", "System", "Audit Other System Events", "-", "M"],
  6402: ["BranchCache: The message to the hosted cache offering it data is incorrectly formatted", "System", "Audit Other System Events", "-", "M"],
  6403: ["BranchCache: The hosted cache sent an incorrectly formatted response to the client", "System", "Audit Other System Events", "-", "M"],
  6404: ["BranchCache: Hosted cache could not be authenticated using the provisioned SSL certificate", "System", "Audit Other System Events", "-", "M"],
  6405: ["BranchCache event instances recorded (see event parameters)", "System", "Audit Other System Events", "-", "M"],
  6406: ["Filtering component registered with Windows Firewall", "System", "Audit Other System Events", "-", "M"],
  6407: ["Windows Firewall integration status message (provider-specific)", "System", "Audit Other System Events", "-", "M"],
  6408: ["Registered filtering product failed; Windows Firewall took over", "System", "Audit Other System Events", "-", "M"],
  6409: ["BranchCache: A service connection point object could not be parsed", "System", "Audit Other System Events", "-", "M"],
  6410: ["Code integrity determined that a file does not meet the security requirements to load into a process", "System", "Audit System Integrity", "F", "M"],
  6416: ["A new external device was recognized by the System", "Detailed Tracking", "Audit PNP Activity", "S", "M"],
  6417: ["FIPS cryptographic self-tests succeeded", "System", "Other System Events", "-", "E"],
  6418: ["FIPS cryptographic self-tests failed", "System", "Other System Events", "-", "E"],
  6419: ["A request was made to disable a device", "Detailed Tracking", "Audit PNP Activity", "S", "M"],
  6420: ["A device was disabled", "Detailed Tracking", "Audit PNP Activity", "S", "M"],
  6421: ["A request was made to enable a device", "Detailed Tracking", "Audit PNP Activity", "S", "M"],
  6422: ["A device was enabled", "Detailed Tracking", "Audit PNP Activity", "S", "M"],
  6423: ["installation of this device is forbidden by system policy", "Detailed Tracking", "Audit PNP Activity", "S", "M"],
  6424: ["installation of this device was allowed, after having previously been forbidden by policy", "Detailed Tracking", "Audit PNP Activity", "S", "M"],
});

// A numeric event ID without a known provider is not sufficient evidence of Sysmon.
// See Microsoft Sysmon event definitions: https://learn.microsoft.com/en-us/sysinternals/downloads/sysmon
export const SYSMON_EVENTS = Object.freeze({
  1: "Process created",
  2: "File creation timestamp changed",
  3: "Network connection detected",
  4: "Sysmon service state changed",
  5: "Process terminated",
  6: "Driver loaded",
  7: "Image loaded",
  8: "Remote thread created",
  9: "Raw disk read",
  10: "Process accessed",
  11: "File created",
  12: "Registry object created or deleted",
  13: "Registry value set",
  14: "Registry object renamed",
  15: "File stream hash captured",
  16: "Sysmon configuration changed",
  17: "Named pipe created",
  18: "Named pipe connected",
  19: "WMI event filter created",
  20: "WMI event consumer created",
  21: "WMI consumer binding created",
  22: "DNS query",
  23: "File deleted with archive",
  24: "Clipboard contents changed",
  25: "Process tampering detected",
  26: "File delete recorded",
});

