// SPDX-License-Identifier: MIT
// HexSpindle original incident-response/log analysis operations.
import { text, safeJson, parseJsonish, recordsFromInput, first, parseXmlFields, xmlTag, xmlAttr, extractIocsFromText, normalizeIndicator } from './_common.js';

const EVENT_INFO = {
  1:['Sysmon','Process creation'],3:['Sysmon','Network connection'],7:['Sysmon','Image loaded'],8:['Sysmon','CreateRemoteThread'],10:['Sysmon','Process access'],11:['Sysmon','File create'],12:['Sysmon','Registry object create/delete'],13:['Sysmon','Registry value set'],22:['Sysmon','DNS query'],
  4624:['Security','Successful logon'],4625:['Security','Failed logon'],4634:['Security','Logoff'],4648:['Security','Logon using explicit credentials'],4672:['Security','Special privileges assigned'],4688:['Security','Process creation'],4697:['Security','Service installed'],4698:['Security','Scheduled task created'],4702:['Security','Scheduled task updated'],4720:['Security','User account created'],4722:['Security','User account enabled'],4724:['Security','Password reset attempted'],4728:['Security','Member added to global group'],4732:['Security','Member added to local group'],4740:['Security','Account locked out'],4768:['Security','Kerberos TGT requested'],4769:['Security','Kerberos service ticket requested'],4771:['Security','Kerberos pre-authentication failed'],4776:['Security','NTLM credential validation'],
  4103:['PowerShell','Module logging'],4104:['PowerShell','Script block logging'],400:['PowerShell','Engine start'],403:['PowerShell','Engine stop'],
  7045:['System','Service installed'],1149:['TerminalServices-RemoteConnectionManager','RDP user authentication succeeded'],
  1116:['Defender','Malware detected'],1117:['Defender','Action taken on malware'],5001:['Defender','Real-time protection disabled'],5007:['Defender','Configuration changed'],5010:['Defender','Scanning for malware disabled'],5012:['Defender','Virus scanning disabled'],
};
export function explainWindowsEventId(data){const s=text(data).trim();const ids=(s.match(/\b\d{1,5}\b/g)||[]).map(Number);const unique=[...new Set(ids)];return safeJson(unique.map(id=>({eventId:id,provider:EVENT_INFO[id]?.[0]||'Unknown',meaning:EVENT_INFO[id]?.[1]||'No built-in explanation',note:'Built-in local reference; verify uncommon/provider-specific semantics against the source system.'})));}

function eventFromXml(xml){const fields=parseXmlFields(xml);const id=Number(xmlTag(xml,'EventID')||fields.EventID||0);const provider=xmlAttr(xml,'Provider','Name')||'';const time=xmlAttr(xml,'TimeCreated','SystemTime')||'';const computer=xmlTag(xml,'Computer')||'';return{eventId:id,provider,time,computer,fields,raw:xml};}
function normalizeObj(o){const sys=o.System||o.system||{};const ed=o.EventData||o.eventData||o.Event||o.event||{};const fields={};if(Array.isArray(ed.Data))for(const x of ed.Data){if(x&&typeof x==='object')fields[x.Name||x.name||x['@Name']||`field${Object.keys(fields).length}`]=x['#text']??x.value??x.Value??'';}else if(ed&&typeof ed==='object')Object.assign(fields,ed);const id=Number(first(o,[["EventID"],["eventId"],["EventId"],["Id"],["System","EventID"],["System","EventID","Value"]],0));const provider=String(first(o,[["ProviderName"],["provider"],["System","Provider","Name"],["System","ProviderName"]],''));const time=String(first(o,[["TimeCreated"],["timestamp"],["SystemTime"],["System","TimeCreated","SystemTime"]],''));return{eventId:id,provider,time,computer:String(first(o,[["Computer"],["System","Computer"]],'')),fields:{...fields,...o},raw:o};}
function events(data){const s=text(data).trim();const out=[];const j=parseJsonish(data);if(j){const arr=Array.isArray(j)?j:(Array.isArray(j.Events)?j.Events:[j]);for(const x of arr)out.push(normalizeObj(x));return out;}for(const m of s.matchAll(/<Event\b[\s\S]*?<\/Event>/gi))out.push(eventFromXml(m[0]));if(!out.length&&/<Event\b/i.test(s))out.push(eventFromXml(s));return out;}
function f(e,...names){for(const n of names){for(const [k,v] of Object.entries(e.fields||{}))if(k.toLowerCase()===n.toLowerCase())return v;}return'';}
export function normalizeSysmon(data){const out=[];for(const e of events(data)){const id=e.eventId;if(!id)continue;out.push({timestamp:e.time,eventId:id,eventType:EVENT_INFO[id]?.[1]||'Sysmon event',computer:e.computer,user:f(e,'User','UserName'),processId:f(e,'ProcessId'),processGuid:f(e,'ProcessGuid'),image:f(e,'Image'),commandLine:f(e,'CommandLine'),parentImage:f(e,'ParentImage'),parentCommandLine:f(e,'ParentCommandLine'),sourceIp:f(e,'SourceIp'),sourcePort:f(e,'SourcePort'),destinationIp:f(e,'DestinationIp'),destinationPort:f(e,'DestinationPort'),queryName:f(e,'QueryName'),targetObject:f(e,'TargetObject'),hashes:f(e,'Hashes')});}return safeJson(out);}
const LOGON_TYPES={2:'Interactive',3:'Network',4:'Batch',5:'Service',7:'Unlock',8:'NetworkCleartext',9:'NewCredentials',10:'RemoteInteractive (RDP)',11:'CachedInteractive'};
export function analyzeWindowsLogons(data){const out=[];for(const e of events(data)){if(![4624,4625,4634,4648,4776].includes(e.eventId))continue;const lt=Number(f(e,'LogonType'));out.push({timestamp:e.time,eventId:e.eventId,result:e.eventId===4624?'success':e.eventId===4625?'failure':'other',user:[f(e,'TargetDomainName'),f(e,'TargetUserName')].filter(Boolean).join('\\'),sourceIp:f(e,'IpAddress','WorkstationName'),sourcePort:f(e,'IpPort'),workstation:f(e,'WorkstationName'),logonType:lt||null,logonTypeName:LOGON_TYPES[lt]||'',authenticationPackage:f(e,'AuthenticationPackageName'),process:f(e,'ProcessName'),status:f(e,'Status'),subStatus:f(e,'SubStatus'),logonId:f(e,'TargetLogonId')});}return safeJson(out);}
export function analyzeKerberos(data){const out=[];for(const e of events(data)){if(![4768,4769,4771].includes(e.eventId))continue;out.push({timestamp:e.time,eventId:e.eventId,type:EVENT_INFO[e.eventId]?.[1],account:f(e,'TargetUserName','AccountName'),service:f(e,'ServiceName'),clientAddress:f(e,'IpAddress','ClientAddress'),ticketEncryptionType:f(e,'TicketEncryptionType'),ticketOptions:f(e,'TicketOptions'),status:f(e,'Status','FailureCode'),preAuthType:f(e,'PreAuthType')});}return safeJson(out);}
export function analyzeRdp(data){const out=[];for(const e of events(data)){const lt=Number(f(e,'LogonType'));if(!(e.eventId===1149||(e.eventId===4624&&lt===10)||[21,22,24,25,39,40].includes(e.eventId)))continue;out.push({timestamp:e.time,eventId:e.eventId,user:f(e,'TargetUserName','User','UserName'),domain:f(e,'TargetDomainName'),sourceIp:f(e,'IpAddress','Address','ClientAddress'),sessionId:f(e,'SessionID','SessionId'),activity:e.eventId===1149?'RDP authentication':e.eventId===4624?'RDP logon':`RDP session event ${e.eventId}`});}return safeJson(out);}
export function detectServiceInstalls(data){const out=[];for(const e of events(data)){if(![7045,4697].includes(e.eventId))continue;out.push({timestamp:e.time,eventId:e.eventId,serviceName:f(e,'ServiceName'),imagePath:f(e,'ImagePath','ServiceFileName'),serviceType:f(e,'ServiceType'),startType:f(e,'StartType','ServiceStartType'),account:f(e,'AccountName','ServiceAccount'),risk:/\\temp\\|appdata|powershell|cmd\.exe|rundll32|mshta|wscript|cscript/i.test(f(e,'ImagePath','ServiceFileName'))?'review':'normal'});}return safeJson(out);}
export function parseScheduledTaskXml(data){const s=text(data);const actions=[];for(const m of s.matchAll(/<Exec\b[\s\S]*?<\/Exec>/gi))actions.push({type:'Exec',command:xmlTag(m[0],'Command'),arguments:xmlTag(m[0],'Arguments'),workingDirectory:xmlTag(m[0],'WorkingDirectory')});for(const m of s.matchAll(/<ComHandler\b[\s\S]*?<\/ComHandler>/gi))actions.push({type:'ComHandler',classId:xmlTag(m[0],'ClassId'),data:xmlTag(m[0],'Data')});const triggers=[];for(const m of s.matchAll(/<(BootTrigger|LogonTrigger|TimeTrigger|CalendarTrigger|EventTrigger|SessionStateChangeTrigger)\b[\s\S]*?<\/\1>/gi))triggers.push({type:m[1],startBoundary:xmlTag(m[0],'StartBoundary'),enabled:xmlTag(m[0],'Enabled'),userId:xmlTag(m[0],'UserId'),subscription:xmlTag(m[0],'Subscription')});return safeJson({uri:xmlTag(s,'URI'),author:xmlTag(s,'Author'),userId:xmlTag(s,'UserId'),runLevel:xmlTag(s,'RunLevel'),logonType:xmlTag(s,'LogonType'),hidden:xmlTag(s,'Hidden'),actions,triggers});}
export function reassemblePowerShell4104(data){const groups=new Map();for(const e of events(data)){if(e.eventId!==4104)continue;const id=String(f(e,'ScriptBlockId')||'unknown'),msg=Number(f(e,'MessageNumber')||1),total=Number(f(e,'MessageTotal')||1),txt=String(f(e,'ScriptBlockText')||f(e,'Message')||'');if(!groups.has(id))groups.set(id,{scriptBlockId:id,total,parts:new Map(),firstTimestamp:e.time});groups.get(id).parts.set(msg,txt);}const out=[];for(const g of groups.values()){const missing=[];for(let i=1;i<=g.total;i++)if(!g.parts.has(i))missing.push(i);out.push({scriptBlockId:g.scriptBlockId,timestamp:g.firstTimestamp,totalParts:g.total,missingParts:missing,complete:missing.length===0,script:Array.from({length:g.total},(_,i)=>g.parts.get(i+1)||'').join('')});}return safeJson(out);}
export function analyzeDefender(data){const out=[];for(const e of events(data)){if(!([1116,1117,1118,1119,5001,5007,5010,5012].includes(e.eventId)||/Defender/i.test(e.provider)))continue;out.push({timestamp:e.time,eventId:e.eventId,meaning:EVENT_INFO[e.eventId]?.[1]||'Defender event',threatName:f(e,'Threat Name','ThreatName'),severity:f(e,'Severity Name','SeverityName'),path:f(e,'Path'),action:f(e,'Action Name','ActionName'),configuration:f(e,'New Value','NewValue'),user:f(e,'Detection User','DetectionUser'),rawFields:e.fields});}return safeJson(out);}

export function parseIis(data){const lines=text(data).split(/\r?\n/),rows=[];let fields=[];for(const line of lines){if(line.startsWith('#Fields:')){fields=line.slice(8).trim().split(/\s+/);continue;}if(!line||line.startsWith('#'))continue;const vals=line.split(/\s+/);const r={};fields.forEach((k,i)=>r[k]=vals[i]??'');r._timestamp=[r.date,r.time].filter(Boolean).join('T');r._suspicious=/\.\.|%2e|cmd=|powershell|\/wp-admin|\/\.git|union(?:\+|%20|\s)+select|<script|jndi:/i.test(line);rows.push(r);}return safeJson(rows);}
export function parseWebAccess(data){const rows=[];for(const line of text(data).split(/\r?\n/)){if(!line.trim())continue;let m=/^(\S+)\s+\S+\s+(\S+)\s+\[([^\]]+)\]\s+"([A-Z]+)\s+([^\s"]+)(?:\s+HTTP\/([\d.]+))?"\s+(\d{3})\s+(\S+)(?:\s+"([^"]*)"\s+"([^"]*)")?/.exec(line);if(!m)m=/^(\S+)\s+-\s+-\s+\[([^\]]+)\]\s+"([A-Z]+)\s+([^\s"]+)\s+HTTP\/([\d.]+)"\s+(\d{3})\s+(\S+)/.exec(line);if(!m){rows.push({raw:line,parsed:false});continue;}const uri=m[4]&&m[1]? (m.length>9?m[5]:m[4]):'';rows.push({remoteIp:m[1],user:m[2]||'',timestamp:m[3]||m[2],method:m[4]||m[3],uri,status:Number(m[7]||m[6]),bytes:m[8]||m[7],referer:m[9]||'',userAgent:m[10]||'',suspicious:/\.\.|%2e|\/\.env|\/\.git|wp-admin|union(?:\+|%20|\s)+select|cmd=|jndi:/i.test(line)});}return safeJson(rows);}
export function analyzeLinuxAuth(data){const rows=[];for(const line of text(data).split(/\r?\n/)){if(!line.trim())continue;let type='other',user='',ip='';let m;if((m=/Failed password for (?:invalid user )?(\S+) from (\S+)/.exec(line))){type='ssh_failure';user=m[1];ip=m[2];}else if((m=/Accepted \S+ for (\S+) from (\S+)/.exec(line))){type='ssh_success';user=m[1];ip=m[2];}else if((m=/sudo: +([^ :]+).*COMMAND=(.*)$/.exec(line))){type='sudo';user=m[1];}else if(/session opened/i.test(line))type='session_open';rows.push({type,user,ip,raw:line});}const summary={sshFailures:rows.filter(x=>x.type==='ssh_failure').length,sshSuccesses:rows.filter(x=>x.type==='ssh_success').length,sudo:rows.filter(x=>x.type==='sudo').length};return safeJson({summary,events:rows});}
export function parseAuditd(data){const groups=new Map();for(const line of text(data).split(/\r?\n/)){const m=/type=(\w+).*msg=audit\(([^:]+):(\d+)\):\s*(.*)/.exec(line);if(!m)continue;const [,type,time,serial,rest]=m;const g=groups.get(serial)||{serial,timestamp:Number(time),records:[]};g.records.push({type,fields:Object.fromEntries([...rest.matchAll(/(\w+)=("[^"]*"|'[^']*'|\S+)/g)].map(x=>[x[1],x[2].replace(/^['"]|['"]$/g,'')]))});groups.set(serial,g);}return safeJson([...groups.values()]);}
export function analyzeMacUnifiedJson(data){const j=parseJsonish(data);const arr=Array.isArray(j)?j:(j?[j]:[]);return safeJson(arr.map(x=>({timestamp:x.timestamp||x.date||x.time||'',process:x.process||x.processImagePath||'',pid:x.processID||x.pid||'',subsystem:x.subsystem||'',category:x.category||'',eventMessage:x.eventMessage||x.message||'',activityIdentifier:x.activityIdentifier||''})));}
export function analyzeCloudTrail(data){const j=parseJsonish(data);const arr=Array.isArray(j)?j:(j?.Records||j?.records||[]);const notable=/^(ConsoleLogin|AssumeRole|CreateUser|CreateAccessKey|PutUserPolicy|AttachUserPolicy|CreateRole|UpdateAssumeRolePolicy|StopLogging|DeleteTrail|PutBucketPolicy|AuthorizeSecurityGroupIngress|RunInstances|CreateFunction|UpdateFunctionCode)$/;return safeJson(arr.map(x=>({eventTime:x.eventTime,eventName:x.eventName,eventSource:x.eventSource,userIdentity:x.userIdentity?.arn||x.userIdentity?.userName||x.userIdentity?.type,sourceIPAddress:x.sourceIPAddress,userAgent:x.userAgent,errorCode:x.errorCode||'',region:x.awsRegion,notable:notable.test(x.eventName||''),requestParameters:x.requestParameters})));}
export function analyzeEntra(data){const arr=recordsFromInput(data);return safeJson(arr.map(x=>({createdDateTime:x.createdDateTime||x.timestamp,user:x.userPrincipalName||x.userDisplayName||x.userId,app:x.appDisplayName||x.resourceDisplayName,ipAddress:x.ipAddress,location:x.location?.city||x.location?.countryOrRegion||x.location,status:x.status?.errorCode??x.resultType,result:x.status?.failureReason||x.resultDescription||'',clientApp:x.clientAppUsed,authenticationRequirement:x.authenticationRequirement,riskLevel:x.riskLevelAggregated||x.riskLevelDuringSignIn,conditionalAccess:x.conditionalAccessStatus,device:x.deviceDetail})));}
export function analyzeM365(data){const arr=recordsFromInput(data);const notable=/MailItemsAccessed|New-InboxRule|Set-InboxRule|Add-MailboxPermission|Set-Mailbox|Consent|Add service principal|UserLoggedIn|FileDownloaded|SharingSet|Role/i;return safeJson(arr.map(x=>({creationTime:x.CreationTime||x.creationTime,operation:x.Operation||x.operation,userId:x.UserId||x.userId,workload:x.Workload||x.workload,clientIp:x.ClientIP||x.clientIp,objectId:x.ObjectId||x.objectId,result:x.ResultStatus||x.resultStatus,notable:notable.test(x.Operation||x.operation||''),raw:x})));}
export function buildTimeline(data){const arr=recordsFromInput(data),out=[];for(const x of arr){const ts=first(x,[["timestamp"],["time"],["eventTime"],["createdDateTime"],["CreationTime"],["lastWrite"],["lastRun"],["deletionTime"]],'');if(!ts)continue;out.push({timestamp:ts,source:x.source||x.artifact||x.provider||x.Workload||'unknown',event:x.event||x.eventName||x.Operation||x.meaning||x.type||x.name||'',actor:x.user||x.userId||x.account||'',target:x.path||x.objectId||x.target||x.image||'',details:x});}out.sort((a,b)=>Date.parse(a.timestamp)-Date.parse(b.timestamp));return safeJson(out);}
export function extractIocContext(data){const s=text(data);const lines=s.split(/\r?\n/),starts=[];let p=0;for(const line of lines){starts.push(p);p+=line.length+1;}const iocs=extractIocsFromText(s);for(const x of iocs){let li=0;while(li+1<starts.length&&starts[li+1]<=x.offset)li++;x.line=li+1;x.context=lines.slice(Math.max(0,li-1),Math.min(lines.length,li+2)).join('\n');}return safeJson(iocs);}
export function dedupeIocs(data){const j=parseJsonish(data);const arr=Array.isArray(j)?j:extractIocsFromText(text(data));const m=new Map();for(const x of arr){const value=normalizeIndicator(x.value||x.indicator||x.ioc||'');if(!value)continue;const type=x.type||'unknown',key=type+'\0'+value.toLowerCase(),r=m.get(key)||{type,value,count:0,sources:[]};r.count++;if(x.source&&!r.sources.includes(x.source))r.sources.push(x.source);m.set(key,r);}return safeJson([...m.values()].sort((a,b)=>b.count-a.count||a.value.localeCompare(b.value)));}

function yamlScalar(s){s=s.trim();if(!s)return{};if(/^['"].*['"]$/.test(s))return s.slice(1,-1);if(/^(true|false)$/i.test(s))return/^true$/i.test(s);if(/^\d+$/.test(s))return Number(s);if(s.startsWith('[')&&s.endsWith(']'))return s.slice(1,-1).split(',').map(x=>yamlScalar(x));return s;}
function tinyYaml(y){const root={};const stack=[[-1,root]];for(const raw of y.split(/\r?\n/)){if(!raw.trim()||/^\s*#/.test(raw))continue;const ind=raw.match(/^\s*/)[0].length;const line=raw.trim();const m=/^([^:]+):(?:\s*(.*))?$/.exec(line);if(!m)continue;while(stack.length&&stack.at(-1)[0]>=ind)stack.pop();const parent=stack.at(-1)[1],key=m[1].trim(),rest=m[2]??'';if(rest===''){parent[key]={};stack.push([ind,parent[key]]);}else parent[key]=yamlScalar(rest);}return root;}
function valMatch(value,cond,op){const vals=Array.isArray(value)?value:[value];const cs=Array.isArray(cond)?cond:[cond];return vals.some(v=>cs.some(c=>{v=String(v??'');c=String(c??'');if(op==='contains')return v.toLowerCase().includes(c.toLowerCase());if(op==='startswith')return v.toLowerCase().startsWith(c.toLowerCase());if(op==='endswith')return v.toLowerCase().endsWith(c.toLowerCase());if(op==='re'){try{return new RegExp(c,'i').test(v);}catch{return false;}}const re='^'+c.replace(/[.+^${}()|[\]\\]/g,'\\$&').replace(/\*/g,'.*').replace(/\?/g,'.')+'$';return new RegExp(re,'i').test(v);}));}
function selectionMatch(rec,sel){return Object.entries(sel).every(([k,c])=>{const [field,op='eq']=k.split('|');let v=rec[field];if(v===undefined){const fkey=Object.keys(rec).find(x=>x.toLowerCase()===field.toLowerCase());v=fkey?rec[fkey]:undefined;}return valMatch(v,c,op);});}
export function evaluateSigmaSubset(data){const s=text(data);const split=s.indexOf('\n---EVENTS---\n');if(split<0)throw new Error('Input must be: Sigma YAML, then a line containing ---EVENTS---, then JSON/JSONL events');const rule=tinyYaml(s.slice(0,split)),evText=s.slice(split+14),arr=(()=>{try{const j=JSON.parse(evText);return Array.isArray(j)?j:[j];}catch{return evText.split(/\r?\n/).filter(Boolean).map(x=>JSON.parse(x));}})();const det=rule.detection||{},condition=String(det.condition||'selection'),sels=Object.fromEntries(Object.entries(det).filter(([k,v])=>k!=='condition'&&v&&typeof v==='object'));function ok(rec){const states=Object.fromEntries(Object.entries(sels).map(([k,v])=>[k,selectionMatch(rec,v)]));let expr=condition.replace(/\b(and|or|not|of|them|all|1)\b/gi,m=>m.toLowerCase());if(/^all of them$/.test(expr))return Object.values(states).every(Boolean);if(/^1 of them$/.test(expr))return Object.values(states).some(Boolean);if(/^[\w\s()]+$/.test(expr)){const js=expr.replace(/\b([A-Za-z_]\w*)\b/g,(m)=>['and','or','not'].includes(m)?({and:'&&',or:'||',not:'!'}[m]):`states[${JSON.stringify(m)}]`);try{return Function('states',`return !!(${js})`)(states);}catch{return false;}}return states[condition]||false;}const hits=arr.filter(ok);return safeJson({title:rule.title||'',condition,selectionNames:Object.keys(sels),matched:hits.length,total:arr.length,hits});}
