import { module } from './_cat.js';

const BY_BITS = {
  4: ['Fletcher-4', 'Luhn algorithm', 'Verhoeff algorithm'],
  8: ['Fletcher-8'],
  16: ['BSD checksum', 'CRC-16', 'SYSV checksum', 'Fletcher-16'],
  32: ['CRC-32', 'Fletcher-32', 'Adler-32'],
  64: ['CRC-64', 'RIPEMD-64', 'SipHash'],
  128: ['MD5', 'MD4', 'MD2', 'HAVAL-128', 'RIPEMD-128', 'Snefru', 'Tiger-128'],
  160: ['SHA-1', 'SHA-0', 'FSB-160', 'HAS-160', 'HAVAL-160', 'RIPEMD-160', 'Tiger-160'],
  192: ['Tiger', 'HAVAL-192'],
  224: ['SHA-224', 'SHA3-224', 'ECOH-224', 'FSB-224', 'HAVAL-224'],
  256: ['SHA-256', 'SHA3-256', 'BLAKE-256', 'ECOH-256', 'FSB-256', 'GOST', 'Grøstl-256', 'HAVAL-256', 'PANAMA', 'RIPEMD-256', 'Snefru'],
  320: ['RIPEMD-320'],
  384: ['SHA-384', 'SHA3-384', 'ECOH-384', 'FSB-384'],
  512: ['SHA-512', 'SHA3-512', 'BLAKE-512', 'ECOH-512', 'FSB-512', 'Grøstl-512', 'JH', 'MD6', 'Spectral Hash', 'SWIFFT', 'Whirlpool'],
  1024: ['Fowler-Noll-Vo'],
};

module('Analyse hash', 'Tries to determine information about a given hash and suggests which algorithm may have been used to generate it based on its length.',
  [],
  (t) => {
    t = t.replace(/\s/g, '');
    const byteLength = t.length / 2, bitLength = byteLength * 8;
    if (!/^[a-f0-9]+$/i.test(t)) throw new Error('Invalid hash');
    return `Hash length: ${t.length}\nByte length: ${byteLength}\nBit length:  ${bitLength}\n\n` +
      'Based on the length, this hash could have been generated by one of the following hashing functions:\n' +
      (BY_BITS[bitLength] || ['Unknown']).join('\n');
  }, { text: true });
